- shared/message/behaviour/Action.h
- shared/message/input/LimbID.h
- shared/message/input/Sensors.h
- shared/utility/motion/ForwardKinematics.h
Explicit includes in the messages to make a minimal build of it possible
Unfortunately i wasn't able to set up the environment, so i could not test in your code if i break something ;). So please try it before merging.  
(Greetings from Hamburg)
> Minor Bugfix in the Forward Kinematics: Missing calculation

- module/tools/FirmwareInstaller/src/FirmwareInstaller.cpp
- shared/utility/strutil/strutil.h
Removing the by reference toupper function as it is very much a Cism.
> Removes the by reference toupper function.

- .travis.yml
> Enable travis slack integration for NUbots

- .gitignore
- tools/install.py
The version file contains the `git log -1` output to show the latest commit hash.
> Send a version file to the robot on install.

- shared/extension/Script.h
Adds some more exception handling to YAML loading.
> Fixes script loading

- module/input/Camera/data/config/gpio_setup.sh
- module/input/Camera/data/config/gpio_toggle.sh
- module/input/Camera/data/gpio_setup.sh
Tony's last pull request failed to fix the problem
> Tony is indeed an idiot

- module/localisation/BallLocalisation/src/BallLocalisation.cpp
- roles/lookatball.role
Code was comparing a cartesian vector against a spherical vector. Changed that, plus changed lookatball.role so that BallLocalisation was run.
> Minor Ball Localisation fix

- puppet/modules/build_tools/manifests/init.pp
- tools/decode.py
This allows the decoder to parse nbs files using the new xxhash system.
It also adds the ability to decode NUsight<> wrapped messages
> Fix the nbs decoder to work with new nbs streams and NUsight

- tools/decode.py
There is a variable for this now
> Update decode.py's path

- module/behaviour/skills/KickScript/src/KickScript.cpp
- module/motion/OldWalkEngine/data/config/igus1/OldWalkEngine.yaml
- module/motion/OldWalkEngine/data/config/igus1/OldWalkEngine_001.yaml
- module/motion/ScriptEngine/data/scripts/igus/KickLeft.yaml
- module/motion/ScriptEngine/data/scripts/igus/KickRight.yaml
Saves the scripted left kick Ysobel and I made and uses the soft kick for the right foot (to be modified)
Also adds initial walk engine tuning versions from Taylor and I, and Tony and I.
> Update kick scripts and walk-engine tuning

- module/vision/BallDetector/src/BallDetector.cpp
- module/vision/GoalDetector/src/GoalDetector.cpp
- module/vision/GreenHorizonDetector/src/GreenHorizonDetector.cpp
- module/vision/VisualMesh/src/VisualMesh.cpp
- roles/robocup.role
- shared/utility/math/geometry/ConvexHull.h
- shared/utility/vision/visualmesh/VisualMesh.h
NUsight needs the rays as columns so it can draw them, so we need to transpose them over here
> Transpose the VM rays so they can be drawn in NUsight fast

- module/platform/darwin/HardwareSimulator/src/HardwareSimulator.cpp
Fixes the gyroscope and accelerometer values in HardwareSimulator.
Includes eigen arma convert.
> Hardware Simulator Fix

- README.md
Changing the pipeline broke the badge.
> Fix the buildkite badge

- nuclear/b.py
- tools/decode.py
- tools/extract_images.py
- tools/footdown.py
- tools/format.py
- tools/install.py
- tools/platform.py
Make the b script commands know when they can't be executed and print an error message if someone attempts to use one.
> Make the b script commands know when they can't be executed

- nuclear/message/Neutron.cmake
- tools/decode.py
- tools/extract_images.py
- tools/nbs_decoder/.gitignore
- tools/nbs_decoder/__init__.py
Improve the nbs decoder so that it can run without the aid of the VM. This opens up more opportunities to use it for manipulating nbs files with less effort.
Also add on code to synchronize on packet headers for malformed or partial nbs streams.
> Improve the nbs decoder so it does not need the VM to run

- nuclear/cmake/Modules/NUClearCompilerSettings.cmake
We need C++17 so that we can stop worrying about Eigen and alignment issues. Currently NUClear Roles is holding us back!
> Upgrade nuclear roles to C++17

- README.md
Required to get cmakelists.txt for VisualMesh submodule, in order to ./b build the codebase.
> Added --recursive flag to git clone in README

- module/support/SoccerSimulator/src/VirtualBall.cpp
- module/vision/BallDetector/src/BallDetector.cpp
- shared/message/Geometry.proto
Radius and gradient are the same number and having both is terrible
> Remove gradient from the cone as as it's duplicate information

- .devcontainer.json
- .vscode/settings.json
Make the spell checker use non-american spelling and add some settings to make the editor better display completion/errors
> Update some Visual Studio Code settings

- .vscode/settings.json
> Added Autosort

- .vscode/settings.json
- cmake/Modules/ToolchainLibraryFinder.cmake
- docker/Dockerfile
- nuclear/cmake/Modules/ToolchainLibraryFinder.cmake
- nuclear/message/build_message_class.py
- nuclear/message/generator/OneOfField.py
- nuclear/message/generator/OneOfType.py
- pyproject.toml
- report/graph/extract_nuclear_info.py
- tools/build.py
- tools/configure.py
- tools/edit.py
- tools/format.py
- tools/install.py
- tools/nbs/calibrate_cameras.py
- tools/nbs/camera_calibration/callback/extrinsic_progress.py
- tools/nbs/camera_calibration/callback/intrinsic_progress.py
- tools/nbs/camera_calibration/model/lens_model.py
- tools/nbs/footdown.py
- tools/nbs/stats.py
- tools/nbs/trim.py
- tools/nbs/video.py
- tools/run.py
- tools/shell.py
- tools/target.py
- tools/tests.py
- tools/utility/nbs/load_nbs.py
- tools/utility/nbs/protobuf_types.py
Upgrades the formatting for python and cmake and applies it
> Upgrade the formatting tools to the latest versions

- nuclear/b.py
Currently, it tells you that it installed and to try again. But we can automate that process and try again for you!
> Make the ./b script keep rerunning itself so long as it thinks it can install a package

- tools/tests.py
Fix `run_on_docker` import to reflect changes in #376
> Update run_on_docker import

- nuclear/message/Neutron.cmake
> Fixed what cmake looks for to work out if it has built the neutrons.

- doc/PacmanCache/docker-compose.yml
- docker/Dockerfile
Adds comments to files where mirrors need to be changed so we can link to file instead of to line.
Related to this [PR](https://github.com/NUbots/NUbook/pull/101)
> Comments for changing mirrors

- module/behaviour/strategy/PS3Walk/src/Joystick.hpp
Removed a macro in favor of a constant expression.
> In joystick remove macros and add constant expression.

- module/platform/webots/Webots/src/Webots.cpp
This doesn't build, because NUClear's clock (which the `ServoTarget`s use) has a different duration to this PRs custom clock, and there's no operator to subtract between the two duration types.
I think this should be along the right track though, and we're going to have to build the custom clock into the other stuff too eventually (perhaps next...)
> More comms suggestions

- module/platform/webots/Webots/src/Webots.cpp
- module/platform/webots/Webots/src/Webots.hpp
> Fix Kip's clock stuff in his branch of my branch.

- shared/utility/motion/InverseKinematics.cpp
Not sure why this can compile if it's going to fail at run time for sure :shrug:
> Fix Keyboardwalk Eigen Error

- shared/message/localisation/Field.proto
This field was changed during the arma purge, and the comments weren't updated
> Fixes Field.proto message comment

- module/behaviour/Controller/src/Controller.cpp
- module/behaviour/tools/ScriptTuner/src/ScriptTuner.cpp
- module/motion/HeadController/src/HeadController.cpp
- module/motion/IKKick/src/IKKick.cpp
- module/motion/QuinticWalk/src/QuinticWalk.cpp
- module/motion/QuinticWalk/src/QuinticWalk.hpp
- module/motion/ScriptEngine/README.md
- module/motion/ScriptEngine/src/ScriptEngine.cpp
- module/platform/Gazebo/src/Gazebo.cpp
- module/platform/darwin/HardwareIO/README.md
- module/platform/darwin/HardwareIO/src/HardwareIO.cpp
- module/platform/darwin/HardwareSimulator/README.md
- module/platform/darwin/HardwareSimulator/src/HardwareSimulator.cpp
- shared/message/behaviour/ServoCommand.proto
`std::vector<ServoTarget>` to `ServoTargets`. 
`std::vector<ServoCommand>` to `ServoCommands`.
> Change from using vectors of ServoTarget to using ServoTargets

- tools/format.py
time for formatting went from 1:59 to 26 seconds on my laptop using this flag. nusight formatting is slow :grimacing:
> Make b format flag to skip nusight

- tools/install.py
Extracted from #468 and improved. Used as follows:
```
./b install ./path/to/local/dir --local
```
> Extend `./b install` to install to local directory

- module/platform/Webots/data/config/webots.yaml
`max_velocity` was missing from the other PR :( so things broke
Updates the server address too, since I don't think this changes? And the port just so it's easier to run.
> Update the Webots config so that it works

- shared/utility/support/hostname.hpp
Fixes a segmentation fault introduced in #491.
> Fix a segmentation fault from hostname.hpp

- CMakeLists.txt
- module/platform/Webots/data/config/webots.yaml
- module/platform/Webots/src/Webots.cpp
- module/platform/Webots/src/Webots.hpp
- shared/clock/clock.cpp
- shared/clock/clock.hpp
Someone should test this, also maybe check that this gives you sim speed factor
const double ratio = static_cast<double>(sim_delta + prev_sim_delta) / static_cast<double>(real_delta + prev_real_delta);
> Here's some velocity things

- module/motion/QuinticWalk/src/QuinticWalk.cpp
- module/motion/QuinticWalk/src/QuinticWalk.hpp
- module/motion/QuinticWalk/src/WalkEngine.cpp
- module/motion/QuinticWalk/src/WalkEngine.hpp
- shared/utility/motion/ForwardKinematics.hpp
- shared/utility/motion/InverseKinematics.cpp
- shared/utility/motion/InverseKinematics.hpp
- shared/utility/motion/splines/Combination.hpp
- shared/utility/motion/splines/Footstep.cpp
- shared/utility/motion/splines/Footstep.hpp
- shared/utility/motion/splines/Polynom.hpp
- shared/utility/motion/splines/SmoothSpline.hpp
- shared/utility/motion/splines/Spline.hpp
- shared/utility/motion/splines/SplineContainer.hpp
- shared/utility/motion/splines/TrajectoryUtils.hpp
`const, constexpr, [[nodiscard]]` are cool. We should use them more.
> Nicer C++ stuff for motion metamodule/utils

- shared/utility/support/ProgressBar.cpp
- shared/utility/support/ProgressBar.hpp
This adds a utility that can be used to display progress bars and update them.
> Add a progress bar utility for longer running tasks

- shared/utility/math/geometry/ConvexHull.hpp
Requires Bidski Odometry fixes
> Segfault Hunter (ref. https://github.com/NUbots/NUbots/pull/104)

- module/localisation/BallLocalisation/src/BallLocalisation.cpp
- module/localisation/BallLocalisation/src/BallModel.hpp
- module/localisation/RobotParticleLocalisation/src/RobotModel.hpp
- module/localisation/RobotParticleLocalisation/src/RobotParticleLocalisation.cpp
- module/localisation/RobotParticleLocalisation/src/RobotParticleLocalisation.hpp
- shared/tests/utility/math/filter/TestFilters.cpp
- shared/tests/utility/math/filter/VanDerPolModel.hpp
- shared/utility/math/filter/ParticleFilter.hpp
- shared/utility/math/geometry/ConvexHull.hpp
Particle filter had a segfault looking at ball localisation
> Fixes particle filter segfault 

- module/input/SensorFilter/data/config/SensorFilter.yaml
- module/input/SensorFilter/src/MotionModel.hpp
- module/input/SensorFilter/src/SensorFilter.cpp
- module/input/SensorFilter/src/SensorFilter.hpp
- module/input/SensorFilter/src/VirtualLoadSensor.hpp
- shared/message/input/Sensors.proto
_High impact software engineering_
> Adds comments and some slightly cleaner constructs to SensorFilter

- module/motion/QuinticWalk/data/config/QuinticWalk.yaml
- module/motion/QuinticWalk/data/config/webots/QuinticWalk.yaml
This adds extra comments to the walk params, and moves the webots specific walk configuration to the proper folder.
> Fix webots walk configuration

- docker/usr/local/package/openblas/g4dnxlarge.sh
- docker/usr/local/toolchain/generate_g4dnxlarge_toolchain.py
- tools/webots.py
`./b webots build webotsrobocup --target g4dnxlarge`
> AWS target for robocup

- module/localisation/RobotParticleLocalisation/data/config/RobotParticleLocalisation.yaml
Changed DEBUG to WARN in RobotParticleLocalisation.yaml to remove annoying logs for @ysims .
> Changed DEBUG in RobotParticleLocalisation.yaml to WARN

- module/input/GameController/data/config/GameController.yaml
- module/motion/ScriptEngine/data/scripts/docker/KickPenalty.yaml
- module/motion/ScriptEngine/data/scripts/webots/KickPenalty.yaml
> Tuned penalty kick

- .github/dependabot.yml
I screwed up the config. #631 is having issues because of a missing field, so I added it in this PR
> Fixes dependabot config by adding required field

- module/support/logging/FileLogHandler/src/FileLogHandler.cpp
- module/support/logging/FileLogHandler/src/FileLogHandler.hpp
This was annoying me on another PR.
> Change FileLogHandler to use snake case.

- tools/format.py
> Format only changed files

- CMakeLists.txt
- module/input/SensorFilter/src/MotionModel.hpp
- module/motion/QuinticWalk/src/WalkEngine.hpp
- nuclear/message/include/message/conversion/proto_matrix.hpp
- shared/utility/math/filter/ParticleFilter.hpp
- shared/utility/motion/splines/Polynom.hpp
- shared/utility/motion/splines/SplineContainer.hpp
I used clang12 (which isn't merged yet), which had some _fresh_ issues. There are some decisions made in here which could do with some review. I'll point those out with comments.
> Fixes clang build

- README.md
Re-wrote the sentence "The team is made up of a multidisciplinary team of students and academics" to flow better.
> Update introduction in README

- tools/utility/dockerise/platform.py
> Undo incorrect fix

- module/behaviour/planning/KickPlanner/src/KickPlanner.cpp
- module/input/Camera/src/Camera.cpp
- module/input/SensorFilter/src/SensorFilter.cpp
- module/localisation/BallLocalisation/src/BallLocalisation.cpp
- module/platform/Webots/src/Webots.cpp
- module/platform/darwin/HardwareIO/src/darwin/Darwin.hpp
- shared/extension/Configuration.hpp
- shared/extension/Script.hpp
- shared/extension/behaviour/commands.hpp
- shared/utility/math/geometry/Quad.hpp
- shared/utility/motion/InverseKinematics.hpp
- shared/utility/motion/splines/Combination.hpp
- shared/utility/vision/Vision.hpp
This PR adds the last of the automated changes suggested by clang-tidy which I liked. There are still a few it will generate fixes for, but each of them does something I don't like. Those will have to be dealt with on a case-by-case basis at some point.
After this one is merged, it will be on to the warnings which it doesn't suggest fixes for. There are many, many of those :weary: :weary:
> Clang-tidy Automated Changes Again

- .github/pull_request_template.md
This PR updates the PR template. The pointless restatement of the title bothered me so I removed it. I added something to the checklist to tell people to title their PR, because that seemed to be worth doing. I also made a capitalisation consistent in there too. 
Have you
> Updates PR template

- module/motion/ScriptEngine/data/scripts/nugus2/StandUpFront.yaml
Fixes committed merge conflict in standupfront script for nugus2
Have you
> Fix NUgus2 standupfront script

- module/platform/cm740/HardwareIO/data/config/nugus2/HardwareIO.yaml
- Adjusted for metal legs
- Adjusts shoulder pitch so horn zero (Zombie) position is straight up (Same as n1 and n3)
> Adds new HardwareIO for nugus2

- module/motion/ScriptEngine/data/scripts/nugus/Stand.yaml
Values were a bit out from side to side for some reason. Sits a lot nicer now
> Makes values mirrored

- module/motion/ScriptEngine/data/scripts/nugus/KickLeft.yaml
- module/motion/ScriptEngine/data/scripts/nugus/KickRight.yaml
- Re-tuned KickrRight
- Made a new KickLeft
- Both are similar, small kicks intended for dribbling
> Tuned kick scripts

- module/behaviour/tools/ScriptTuner/src/ScriptTuner.hpp
- module/motion/ScriptEngine/data/scripts/nugus/Stand.yaml
This PR simply lowers default gain set in script tuner.
> Lower scripttuner default gains

- module/platform/cm740/HardwareIO/data/config/nugus3/HardwareIO.yaml
Stood robots side by side to match up the stances when zombied.
> Adjusted n3 hardwareIO

- module/motion/ScriptEngine/data/scripts/nugus1/StandUpFront.yaml
- module/motion/ScriptEngine/data/scripts/nugus2/StandUpFront.yaml
- module/motion/ScriptEngine/data/scripts/nugus3/StandUpFront.yaml
Updates standup scripts now that metal legs are on all robots
Have you
> Update script tunes june 2022 round two, electric boogaloo

- .github/pull_request_template.md
> Update documentation directives link in PR template

- module/support/configuration/GlobalConfig/data/config/GlobalConfig.yaml
It is 1, because we are number 1!!!
see here for team ids for this year:
https://github.com/RoboCup-Humanoid-TC/GameController/blob/master/resources/config/hl_kid/teams.cfg
> Update our team id for RoboCup 2022

- .github/workflows/dockerhub-cleanup.yaml
- .github/workflows/scripts/remove_dockerhub_tag.sh
> removed test changes

- README.md
Make the [codedocs](https://codedocs.nubots.net/) more visible.
> Add codedocs link to readme.

- module/vision/VisualMesh/data/config/nugus/VisualMesh.yaml
- Removing because of computational speed
- Remove right eye in visual mesh
> Removed right camera from visual mesh

- module/motion/ScriptEngine/data/scripts/nugus/Zombie.yaml
New `yaml` update does not like that there is no provided value.
> Add torque values to Zombie.yaml

- nusight2/src/client/components/checkbox_tree/checkbox_tree.stories.tsx
- nusight2/src/client/components/checkbox_tree/tree_node/style.css
I think the CheckboxTree component was created before Storybook, and currently has no stories. This PR adds a story that demonstrates how it's used.
Also improves label styling to enable ellipsis truncation when the label text is longer than the available space.
> Add a story for the CheckboxTree component in NUsight

- nuclear/roles/CMakeLists.txt
- nuclear/roles/NUClearRole.cmake
- nuclear/roles/generate_role.py
- tools/install.py
Things the PR does
- Allows roles to be organised into folders
- Overlaps #866 
Have you
> Allow roles to be split up into folders

- module/motion/ScriptEngine/data/scripts/nugus/DiveLeft.yaml
- module/motion/ScriptEngine/data/scripts/nugus/DiveRight.yaml
This was mainly for quick a demonstration but they turned out pretty good so i think they are worth keeping.
Fall is pretty soft as it does more of a fall than a dive. 
Also set gains to 0 for the final frame.
> Adds left and right goalie dive scripts

- module/extension/Director/src/Director.hpp
- module/extension/Director/src/director/remove_task.cpp
- module/extension/Director/src/director/run_task_pack.cpp
- module/extension/Director/src/information/get_group_info.cpp
- module/extension/Director/src/provider/ProviderGroup.hpp
- module/extension/Director/tests/done_ladder.cpp
- module/extension/Director/tests/done_reset.cpp
- module/extension/Director/tests/util/lcs.hpp
- shared/extension/Behaviour.hpp
- shared/extension/behaviour/InformationSource.hpp
Fixes up the Uses<X> word so that it provides information.
Adds the done state of the group to the Uses information so it can be used to determine when specific subtasks are done
> Add information in Director Uses word to know if a group is done

- tools/run.py
- tools/utility/dockerise/run.py
This pr restricts the b run command argument to require a role.  This improves command-line completion and the help message.
> Add tab completion for b run command

- Downloads
- sped up the first couple of frames
- leaned back in the last frame to stop from falling backwards
> Adjusted nugus3 right kick for stability

- module/actuation/Kinematics/src/Kinematics.cpp
- module/skill/Look/CMakeLists.txt
- module/skill/Look/README.md
- module/skill/Look/data/config/Look.yaml
- module/skill/Look/src/Look.cpp
- module/skill/Look/src/Look.hpp
- module/skill/Look/tests/Look.cpp
- shared/message/skill/Look.proto
- shared/utility/math/coordinates.hpp
This PR adds The Director Look skill, which is similar to the current HeadController module.
- Moved the angle bounds checking into the Kinematics module
- Made a Look message with a direction and smoothing bool
- Made a Look module that takes the direction and smooths if requested then emits a HeadIK Task
Has been tested with ball direction vector and it does follow the ball, functionality the same as the current stuff.
> Adds a Director-style Look skill

- .github/workflows/nubots.yaml
- .github/workflows/nusight.yaml
I don't know if this is right. Pls work.
> Add merge queue github actions

- module/behaviour/planning/SimpleWalkPathPlanner/data/config/webots/SimpleWalkPathPlanner.yaml
- module/behaviour/strategy/SoccerStrategy/data/config/SoccerStrategy.yaml
Hasn't been updated since making a faster walk. Made it walk faster (otherwise it walks on the spot) and reduced the time to walk in ready so it stops before the center.
High priority for the virtual season.
> Tune the ready state configuration values for webots

- module/extension/Director/src/Director.cpp
- module/extension/Director/src/Director.hpp
- module/extension/Director/src/component/DirectorTask.hpp
- module/extension/Director/src/component/Provider.hpp
- module/extension/Director/src/component/ProviderGroup.hpp
- module/extension/Director/src/director/challenge_priority.cpp
- module/extension/Director/src/director/direct_priority.cpp
- module/extension/Director/src/director/find_ok_solution.cpp
- module/extension/Director/src/director/reevaluate_group.cpp
- module/extension/Director/src/director/remove_task.cpp
- module/extension/Director/src/director/run_task_on_provider.cpp
- module/extension/Director/src/director/run_task_pack.cpp
- module/extension/Director/src/director/solve.cpp
- module/extension/Director/tests/change_subtask.cpp
Added a test - fails on main - and added a fix to get working. Makes a DirectorTask which lives in Director and contains the BehaviourTask info as well as Director algorithm specific functionality.
> Fixes a director bug where a task does not get removed when its sibling takes over

- module/planning/PlanWalkPath/data/config/webots/PlanWalkPath.yaml
- module/planning/PlanWalkPath/src/PlanWalkPath.cpp
- module/planning/PlanWalkPath/src/PlanWalkPath.hpp
- module/purpose/Soccer/src/Soccer.cpp
- shared/utility/skill/scripts/webots/KickRight.yaml
Adds 
- Director ramping (slowing near ball, ramping up speed far away from ball)
- Comment out stand still in penalisation bc it causes a director bug (commented because we need to put it back in for the real robot)
- Adds a better right kick for webots
> Add director ramp up speed 

- docker/Dockerfile
- module/network/NetworkForwarder/src/generate_handles.py
- module/support/logging/DataLogging/src/generate_datalogging.py
- module/support/logging/DataPlayback/src/generate_dataplayback.py
Unfortunately one of the updates in #1090 relied on changes that are still stuck in #934 specifically the protocol buffer updates that include this patch https://github.com/protocolbuffers/protobuf/pull/10414
Without these ninja gets super confused and keeps rebuilding the protocol buffers over and over again.
This PR extracts just that change to fix the issue.
> Update protobuf to fix repeated message building

- module/platform/OpenCR/HardwareIO/src/Convert.cpp
- module/platform/OpenCR/HardwareIO/src/hardwareio/process_data.cpp
This PR updates the acceleration conversion function and orientation of the IMU axis.
> OpenCR IMU

- tools/utility/dockerise/run.py
An attempt to make setting the docker hostname to `webots` a little neater. Still not a great solution
> Make docker hostname a little neater

- nusight2/build_scripts/generate_messages.js
pbjs was unhappy about windows directory separators.
> Fix protobuf on windows

- nusight2/src/client/components/localisation/network.ts
- nusight2/src/client/components/localisation/robot_model.ts
- nusight2/src/client/components/localisation/view_model.ts
- nusight2/src/shared/math/vector3.ts
https://github.com/NUbots/NUbots/assets/132620/f2aa671f-f034-40f5-9d7d-343782bada5f
> NUsight: Add field line projection to localisation

- module/planning/FallingRelaxPlanner/data/config/FallingRelaxPlanner.yaml
- module/planning/FallingRelaxPlanner/src/FallingRelaxPlanner.cpp
Robot kept trying to relax all the time so this fixes that
> Falling relax tuning

- module/strategy/FallRecovery/src/FallRecovery.cpp
Causes issues, is very annoying, someone can look at it later and get it working properly.
> Remove falling relax from fall management

- module/input/GameController/src/GameController.cpp
- module/input/GameController/src/GameController.hpp
- module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp
- module/platform/OpenCR/HardwareIO/src/HardwareIO.hpp
- module/platform/cm740/HardwareIO/src/cm740/UART.cpp
> Receive is spelt EI not IE

- module/actuation/FootController/data/config/FootController.yaml
- module/platform/OpenCR/HardwareIO/data/config/nugus4/HardwareIO.yaml
- module/skill/Walk/data/config/Walk.yaml
This PR adds some tunes walk for nugus4 (billie):
- Adds offsets in HardwareIO
- Tunes `Walk.yaml`
- Reduces gain in `FootController`
> Walk tuning

- nusight2/src/client/components/localisation/field/model.ts
- nusight2/src/client/components/localisation/nugus_robot/view.tsx
- nusight2/src/client/components/localisation/skybox/view.tsx
> NUsight2: Update localisation colours

- module/platform/OpenCR/HardwareIO/data/config/nugus3/HardwareIO.yaml
- module/skill/Walk/data/config/Walk.yaml
- module/skill/Walk/data/config/nugus3/Walk.yaml
This PR tunes hardwareio and walk for nugus3 (sarah).
> Add tuning for nugus3

- module/skill/Walk/data/config/nugus1/Walk.yaml
This PR adds walk tune for nugus1
> Add walk tune for nugus1

- module/platform/OpenCR/HardwareIO/data/config/nugus1/HardwareIO.yaml
> Frankie HardwareIO tuning pitch and yaw

- module/tools/SystemConfiguration/data/system/default/etc/wpa_supplicant/wpa_supplicant-wlp0s20f3.conf
- module/tools/SystemConfiguration/data/system/nugus1/etc/systemd/network/30-wifi.network
- module/tools/SystemConfiguration/data/system/nugus1/etc/systemd/network/40-wifi-robocup.network
- module/tools/SystemConfiguration/data/system/nugus2/etc/systemd/network/30-wifi.network
- module/tools/SystemConfiguration/data/system/nugus2/etc/systemd/network/40-wifi-robocup.network
- module/tools/SystemConfiguration/data/system/nugus3/etc/systemd/network/30-wifi.network
- module/tools/SystemConfiguration/data/system/nugus3/etc/systemd/network/40-wifi-robocup.network
- module/tools/SystemConfiguration/data/system/nugus4/etc/systemd/network/30-wifi.network
- module/tools/SystemConfiguration/data/system/nugus4/etc/systemd/network/40-wifi-robocup.network
Sets the wireless networking for RoboCup 2023
> Setup wireless networks for RoboCup competition

- module/support/configuration/SoccerConfig/data/config/LabField.yaml
- module/support/configuration/SoccerConfig/data/config/webots/FieldDescription.yaml
Update field description to use full sized field by default.
> Update field description

- module/vision/VisualMesh/src/VisualMesh.cpp
- module/vision/VisualMesh/src/VisualMesh.hpp
- module/vision/VisualMesh/src/visualmesh/VisualMeshRunner.cpp
- module/vision/VisualMesh/src/visualmesh/VisualMeshRunner.hpp
Adds rate states to the Visual Mesh and updates it to use the same method of concurrent access as ImageCompressor
> Add rate stats to the VisualMesh and update its locking method

- shared/utility/skill/scripts/nugus/StandUpBack.yaml
- shared/utility/skill/scripts/nugus3/StandUpFront.yaml
Front is in the nugus3 folder. Back is in the nugus default folder. Hopefully both will work for all robots
> Adds getups tuned on Sarah.

- module/planning/PlanLook/data/config/PlanLook.yaml
Makes the robot scan left and right when looking for the ball, instead of also looking up and down
> PlanLook Improvements

- module/skill/Walk/data/config/nugus3/Walk.yaml
> Tune kevin walk

- module/planning/PlanWalkPath/data/config/PlanWalkPath.yaml
> Add pivot for billie

- module/platform/OpenCR/HardwareIO/data/config/nugus1/HardwareIO.yaml
- module/platform/cm740/HardwareIO/data/config/nugus1/HardwareIO.yaml
> Rewrote the HardwareIO for nugus1 with Sarah since we swapped NUCs.

- shared/utility/skill/scripts/nugus/Parkour.yaml
> Just the script for getting on the block

- module/input/Camera/data/config/Cameras/Left.yaml
- module/input/Camera/data/config/Cameras/Right.yaml
This PR reduces the AcquisitionFrameRate and DeviceLinkThroughputLimit to match settings used in competition branch.
> Update camera settings

- module/planning/GetUpPlanner/data/config/GetUpPlanner.yaml
- module/planning/GetUpPlanner/src/GetUpPlanner.cpp
- module/planning/GetUpPlanner/src/GetUpPlanner.hpp
Mostly pulled from the robocup2023 branch. Current one doesn't work, but old one is pretty reliable.
> Revert to pre-Director get up detection method

- module/actuation/Kinematics/data/config/Kinematics.yaml
- module/actuation/Kinematics/data/config/nugus/Kinematics.yaml
- module/input/SensorFilter/data/config/SensorFilter.yaml
- module/input/SensorFilter/data/config/nugus/SensorFilter.yaml
- roles/fake/keyboardwalk.role
This pull request 
- changes the urdf model paths around so that the fake keyboard walk does not segfault.
- Adds modules for NUsight in the role
> Fixes fake/keyboardwalk role for getting started page task

- nusight2/src/client/components/localisation/network.ts
- nusight2/src/client/components/localisation/robot_model.ts
- nusight2/src/client/components/localisation/view.tsx
This PR adds ball visualisation to the localisation view. This PR also updates the field space transform of both field line points and ball to be computed property.
> Add visualisation of the ball in NUsight localisation view

- module/actuation/FootController/src/FootController.cpp
- module/actuation/Kinematics/src/Kinematics.cpp
- module/input/SensorFilter/src/sensorfilter/KalmanFilter.cpp
- module/input/SensorFilter/tests/SensorFilter.cpp
- module/motion/IKKick/src/IKKick.cpp
- module/skill/QuinticWalk/src/QuinticWalk.cpp
- shared/tests/utility/actuation/TestKinematics.cpp
- shared/utility/actuation/InverseKinematics.hpp
- shared/utility/math/angle.hpp
This PR cleans up the analytical IK utility, adds comments and fixes up conventions. Additionally, it makes use of the numerically stable `angle_between` function added in https://github.com/NUbots/NUbots/pull/1250
> Clean up analytical IK utility

- module/planning/PlanKick/data/config/webots/PlanKick.yaml
- module/planning/PlanWalkPath/data/config/webots/PlanWalkPath.yaml
This PR tunes the walk path planner and kicking planner to more reliably kick the ball in webots.
> Tune webots kicking and walk path

- shared/utility/skill/scripts/nugus/Stand.yaml
> Adjusted ankle pitch forward

- roles/test/behaviour.role
- roles/webots/behaviour.role
This PR adds NUsight modules to behaviour role for debugging. 
TODO:
> Add NUsight to behaviour role

- module/vision/BallDetector/data/config/BallDetector.yaml
A very small PR but improves detection a lot.
> Tunes the ball detector a smidge

- module/platform/OpenCR/HardwareIO/data/config/nugus1/HardwareIO.yaml
- module/skill/Walk/data/config/nugus1/Walk.yaml
- levels frankie's feet, so they are together
- this has changed the settings on the left hip pitch
> Improve frankies walk 

- module/skill/SplineKick/data/config/nugus4/SplineKick.yaml
It's not perfect but it's sometimes stable, which is a big improvement from main which is very unstable for Frankie to the point where holding it to keep it stable doesn't work very well.
> Add a kick for Frankie

- module/input/Camera/data/config/Cameras/Left.yaml
- module/input/Camera/data/config/Cameras/Right.yaml
- module/vision/Yolo/data/config/Yolo.yaml
Tune yolo slightly for lab environment and increase camera FPS from 10 to 30.
> Tune vision

- module/platform/OpenCR/HardwareIO/data/config/nugus1/HardwareIO.yaml
- module/skill/SplineKick/data/config/nugus1/SplineKick.yaml
Kevin's arms have been out for a while which affects the getup. Hip change was to align the feet better to improve the mirroring on the kick.
> Slight tune to Kevin's HardwareIO and tunes SplineKick on Kevin

- module/input/Camera/data/config/kevin/Cameras/Left.yaml
Update kevin camera kinematics
> Update kevin camera kinematics

- module/skill/SplineKick/data/config/kevin/SplineKick.yaml
Looks pretty good. Made it faster. Tested many times with both feet and seemed good every time. Better on the left foot, sometimes with the right as it places its foot back it spins rather than stopping smoothly.
> Tune Kevin's kick

- module/localisation/FieldLocalisationNLopt/data/config/FieldLocalisationNLopt.yaml
- module/localisation/FieldLocalisationNLopt/data/config/webots/FieldLocalisationNLopt.yaml
- module/localisation/FieldLocalisationNLopt/src/FieldLocalisationNLopt.cpp
- module/localisation/FieldLocalisationNLopt/src/FieldLocalisationNLopt.hpp
- roles/test/localisation.role
- roles/webots/localisation.role
This PR adds a goal measurement update to FieldLocalisationNLOPT. If a pair of goals are detected which are roughly the expected distance apart, a distance cost is added to the cost function for the goal post distance error.
> Add goal measurement update to FieldLocalisationNLOPT

- module/actuation/FootController/data/config/FootController.yaml
- module/actuation/FootController/src/FootController.cpp
- module/actuation/FootController/src/FootController.hpp
- module/purpose/KeyboardWalk/src/KeyboardWalk.cpp
- module/purpose/Soccer/src/Soccer.cpp
Start safely is currently causing a seg fault when finishing some times. This PR reverts to old start safely method in foot controller.
> Revert to low gain startup

- module/purpose/Soccer/src/Soccer.cpp
Otherwise our robot just stands all the time
> Make idle stand have a lower priority to find purpose

- module/purpose/Defender/data/config/Defender.yaml
- module/purpose/Defender/data/config/nugus2/Defender.yaml
- module/purpose/Defender/data/config/nugus3/Defender.yaml
- module/purpose/Defender/src/Defender.cpp
- module/purpose/Defender/src/Defender.hpp
- module/strategy/WalkInsideBoundedBox/src/WalkInsideBoundedBox.cpp
- shared/message/strategy/WalkInsideBoundedBox.proto
This PR aims to make way for some new team based behaviour by having the higher level module tell the bounded box module what the bounded box should be. This will allow us to set different bounding boxes for striker and defender.
> Have bounded box in message of WalkInsideBoundedBox

- module/purpose/Defender/data/config/nugus2/Defender.yaml
- module/purpose/Defender/data/config/nugus3/Defender.yaml
- module/purpose/Defender/src/Defender.cpp
Remove extra yaml's as we only have one Defender, soon to be dynamically decided
> Remove unnecessary Defender configs

- module/network/RobotCommunication/src/RobotCommunication.cpp
- module/purpose/Soccer/src/Soccer.cpp
- nusight2/src/client/components/localisation/controller.ts
- nusight2/src/client/components/localisation/model.ts
- nusight2/src/client/components/localisation/network.ts
- nusight2/src/client/components/localisation/robot_model.ts
- nusight2/src/client/components/localisation/view.tsx
- shared/message/purpose/Purpose.proto
This PR adds the player id and assigns a different colour to some elements in localisation view to help distinguish between bounding boxes when running multiple robots.
> Add debug information for purposes in localisation view

- module/input/SensorFilter/src/SensorFilter.cpp
Buttons didn't work for idle stuff and this fixes it :+1:
> Make buttons work

- module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp
We were having issues with the robots having heaps of dropped packets in HardwareIO and this seemed to fix it
> Make HardwareIO MainThread'd

- module/purpose/Tester/data/config/Tester.yaml
- module/purpose/Tester/src/Tester.cpp
- module/purpose/Tester/src/Tester.hpp
- module/skill/Walk/data/config/webots/Walk.yaml
- roles/robocup.role
Specifically
- Webots arms gains to 30 to stop falling over
- Tester adding walk in bounded box
- Add robot communication to robocup role
This helps make way for NUbots#1378
> Small cleanups

- shared/utility/platform/robot_names.yaml
Sarah and Billie NUCs were swapped, this PR updates their hostname mapping.
> Swap sarah and billie nugus hostnames

- roles/test/behaviour.role
- roles/webots/behaviour.role
Missed in a previous PR. From NUbots#1378
> Add walk in bounded box to behaviour roles

- module/purpose/Soccer/src/Soccer.cpp
Moving over from NUbots#1378. Just simplifying things a little.
> Simplify the dynamic purpose function a little

- nusight2/src/client/components/temp_monitor/controller.ts
- nusight2/src/client/components/temp_monitor/create.tsx
- nusight2/src/client/components/temp_monitor/icon.tsx
- nusight2/src/client/components/temp_monitor/install.tsx
- nusight2/src/client/components/temp_monitor/model.ts
- nusight2/src/client/components/temp_monitor/network.ts
- nusight2/src/client/components/temp_monitor/view.tsx
- nusight2/src/client/main.tsx
> Add servo temperature monitor tab

- .devcontainer.json
Corrects the path to the docker image to allow for opening in dev container in vscode
> Fix VSCode dev container integration

- module/input/SensorFilter/data/config/SensorFilter.yaml
- module/input/SensorFilter/src/SensorFilter.cpp
This makes us not ignore button presses if we have subcontroller errors, just let the debouncing and laws of probability help us there. Also lower debounce threshold slightly, kinda just on vibes. Slight refactor for readability too.
Tested and working on lil Kev :)
> We did it! The buttons will never break again! It's the last button fix!

- nusight2/src/client/components/temp_monitor/view.tsx
Make the temperature monitor boxes in NUsight red when temperature exceeds 50 degrees
> NUsight temperature monitor red warning boxes

- nusight2/src/client/components/temp_monitor/controller.ts
- nusight2/src/client/components/temp_monitor/create.tsx
- nusight2/src/client/components/temp_monitor/icon.tsx
- nusight2/src/client/components/temp_monitor/install.tsx
- nusight2/src/client/components/temp_monitor/model.ts
- nusight2/src/client/components/temp_monitor/network.ts
- nusight2/src/client/components/temp_monitor/view.tsx
- nusight2/src/client/main.tsx
This PR adds a temperature monitor tab for the servos in NUsight
> Add temperature monitor tab to nusight

- module/input/SensorFilter/src/SensorFilter.cpp
Basically the same as #1465 
This makes us not ignore button presses if we have subcontroller errors, just let the debouncing and laws of probability help us there. Also lower debounce threshold slightly, kinda just on vibes. Slight refactor for readability too.
> Copy over button fixes from Robocup PR #1465

- module/planning/PlanWalkPath/data/config/PlanWalkPath.yaml
- module/planning/PlanWalkPath/src/PlanWalkPath.cpp
- module/skill/Walk/data/config/Walk.yaml
- module/skill/Walk/data/config/frankie/Walk.yaml
- module/skill/Walk/src/Walk.cpp
- Walk tuning
- Path plan tuning from RoboCup
- Small bug fixes from RoboCup
> Motion Tuning

- module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp
- module/platform/OpenCR/HardwareIO/src/HardwareIO.hpp
> Use a thread pool in HardwareIO

- .vscode/settings.json
- nusight2/src/client/base/tests/disposable_computed.tests.ts
- nusight2/src/client/network/tests/network.tests.ts
- nusight2/src/client/network/tests/nusight_network.tests.ts
- nusight2/src/client/network/tests/rpc_client.tests.ts
- nusight2/src/client/nuclearnet/tests/web_socket_proxy_nuclearnet_client.tests.ts
- nusight2/src/server/file_picker/list_files.ts
- nusight2/src/server/nbs_scrubber/packet_synthesis.ts
- nusight2/src/server/nbs_scrubber/scrubber_set.ts
- nusight2/src/server/nbs_scrubber/tests/test_utils.ts
- nusight2/src/server/nuclearnet/fake_nuclearnet_client.ts
- nusight2/src/server/nuclearnet/fake_nuclearnet_server.ts
- nusight2/src/server/nuclearnet/tests/decode_packet_id.tests.ts
- nusight2/src/server/nuclearnet/tests/hash_type.tests.ts
- nusight2/src/server/nuclearnet/tests/packet_processor.tests.ts
- nusight2/src/server/session/session_network.ts
- nusight2/src/server/session/tests/nusight_session.tests.ts
- nusight2/src/server/session/tests/session_network.tests.ts
- nusight2/src/server/session/tests/test_utils.ts
- nusight2/src/shared/math/matrix2.ts
- nusight2/src/shared/math/matrix3.ts
- nusight2/src/shared/math/tests/projection.tests.ts
- nusight2/src/shared/math/tests/vector3.tests.ts
- nusight2/src/shared/math/vector3.ts
- nusight2/src/shared/messages/proto/google/protobuf/duration.proto
- nusight2/src/shared/messages/proto/google/protobuf/timestamp.proto
- nusight2/src/shared/nuclearnet/hash_type.ts
- shared/message/network/Test.proto
This PR updates some minor difference between the codebases so that future diffs are easier to read.
These changes should mostly be minor things that won't change the functionality of NUsight itself
> Perform some minor fixes to the code to reduce future diffs

- module/nbs/Player/src/Player.cpp
- module/nbs/Player/src/Player.hpp
- module/support/logging/DataLogging/src/DataLogging.cpp
- module/support/logging/DataLogging/src/DataLogging.hpp
- module/support/logging/FileLogHandler/src/FileLogHandler.cpp
- module/tools/NBSPlayback/src/NBSPlayback.cpp
- shared/message/nbs/player/Player.proto
This PR allows other modules to request the playback of NBS files in a generic manner. For example, for camera calibration or optimization routines.
Additionally, some minor fixes in datalogging and fileloghandler.
> Update NBS player and logging modules

- docker/Dockerfile
- module/tools/LocalisationBenchmark/CMakeLists.txt
- module/tools/LocalisationBenchmark/README.md
- module/tools/LocalisationBenchmark/data/config/LocalisationBenchmark.yaml
- module/tools/LocalisationBenchmark/src/LocalisationBenchmark.cpp
- module/tools/LocalisationBenchmark/src/LocalisationBenchmark.hpp
- roles/webots/localisation_benchmark.role
- roles/webots/logging.role
- tools/optimise_localisation.py
- tools/requirements.map
- tools/requirements.txt
This PR introduces a new utility module, `LocalisationBenchmark`, designed to evaluate the accuracy of the robot's field localisation system by comparing its estimates against ground truth data during NBS file playback. This tool is critical for validating localisation performance and tuning parameters during development.
- **RMSE Metrics**: Computes Root Mean Square Error (RMSE) for:
- Overall translation (3D position) and rotation (orientation)
- Individual degrees of freedom (x, y, z, roll, pitch, yaw)
- **NBS Playback Integration**: Works with NUbots' playback system to process recorded sensor and ground truth data.
- **Optimization Script**: Includes `optimise_localisation` script to automatically tune localisation parameters using genetic algorithms.
1. **New Module**: Added …
> Add LocalisationBenchmark module and GA optimisation script

- module/support/configuration/SoccerConfig/data/config/FieldDescription.yaml
- nusight2/src/client/components/localisation/controller.ts
This PR updates field dimensions for new lab field.
> Update lab field dimensions

- module/input/SensorFilter/data/config/SensorFilter.yaml
- module/input/SensorFilter/data/config/webots/SensorFilter.yaml
- module/input/SensorFilter/src/SensorFilter.cpp
- module/input/SensorFilter/src/SensorFilter.hpp
- module/tools/OdometryBenchmark/CMakeLists.txt
- module/tools/OdometryBenchmark/README.md
- module/tools/OdometryBenchmark/data/config/OdometryBenchmark.yaml
- module/tools/OdometryBenchmark/src/OdometryBenchmark.cpp
- module/tools/OdometryBenchmark/src/OdometryBenchmark.hpp
- roles/webots/odometry_benchmark.role
- tools/optimise_odometry.py
Similar to recent tools added for optimising localisation parameters, this PR adds tools for optimising the parameters for odometry, currently only the `Kp` and `Ki` parameters of the Mahony filter and optimises the roll and pitch error only.
Future PR will include yaw once we update to use Mahony filter estimate.
> Add sensor filter optimisation tools

- poetry.lock
- pyproject.toml
This PR updates optuna version from `0.12.0` to `4.3.0`
> Update optuna version

- poetry.lock
- pyproject.toml
- tools/multi.py
A couple of recent PRs broke the multi robot tool, so this PR fixes them. Adds in colorama to the python libraries and changes run to be async.
> Fix Multi Robot Tool (async and poetry python library)

- module/input/Camera/data/config/Cameras/Left.yaml
- module/input/Camera/data/config/frankie/Cameras/Left.yaml
- module/output/ImageCompressor/data/config/nugus/ImageCompressor.yaml
- module/vision/Yolo/data/config/Yolo.yaml
- roles/robocup.role
Some parameter tuning for the new lab
Also, opencl image compressor is broken so switched to turbojpeg for now
> Parameter tuning for the new lab

- module/input/NatNet/README.md
- module/input/NatNet/data/config/NatNet.yaml
- module/input/NatNet/src/NatNet.cpp
- module/input/SensorFilter/src/SensorFilter.cpp
- module/input/SensorFilter/src/SensorFilter.hpp
- module/localisation/FieldLocalisationNLopt/src/FieldLocalisationNLopt.cpp
- module/localisation/FieldLocalisationNLopt/src/FieldLocalisationNLopt.hpp
- module/localisation/Mocap/CMakeLists.txt
- module/localisation/Mocap/README.md
- module/localisation/Mocap/data/config/Mocap.yaml
- module/localisation/Mocap/src/Mocap.cpp
- module/localisation/Mocap/src/Mocap.hpp
- module/platform/Webots/src/Webots.cpp
- module/tools/LocalisationBenchmark/src/LocalisationBenchmark.cpp
- roles/natnet.role
- roles/webots/localisation.role
- shared/message/localisation/Field.proto
- shared/message/platform/RawSensors.proto
- shared/message/platform/webots/messages.proto
This PR updates ground truth pose logic to work with both webots and optitrack motion capture data. Also some minor changes and instructions for obtaining data from the motive software.
TODO:
- Make same changes to the `FieldLocalisation` module
Associated webots PR https://github.com/NUbots/NUWebots/pull/118
> Mocap ground truth localisation 

- nusight2/package.json
- nusight2/yarn.lock
> Bump nuclearnet.js to 1.7.2

- module/localisation/RobotLocalisation/src/RobotLocalisation.cpp
We seemed to have a bit of repetition in emitting localisation robots and running debug info in the VisionRobots and RoboCup reactions. This PR moves it to just emit run debug info in the main update loop.
> Emit localisation in the main update loop rather than on new information updates

- module/skill/GetUp/data/config/GetUp.yaml
> reduce getup delay by half

- module/purpose/FieldPlayer/data/config/FieldPlayer.yaml
After going over it, the logic is fine. Just needed tuning to allow for localisation errors.
> Turns up center circle offset

- module/localisation/BallLocalisation/data/config/BallLocalisation.yaml
- module/localisation/BallLocalisation/src/BallLocalisation.cpp
- module/localisation/BallLocalisation/src/BallLocalisation.hpp
- module/network/RobotCommunication/src/RobotCommunication.cpp
- Builds
- Cleans up hardcoding, variables that aren't needed
- Simplifies the code a little / cuts down lines
I think this is important to finish because non-attack players can't really see the ball. I had a look in my current support player branch I've got, and it seemed to fix my issue with players searching for the ball unnecessarily.
> [Merge into feature branch] Clean up robot to robot balls

- module/support/configuration/GlobalConfig/data/config/webots/GlobalConfig.yaml
- tools/multi.py
No reason not to, and the new GameController doesn't have config for virtual anyway.
> Switch webots to use team ID of 1, to match normal games

- module/purpose/FieldPlayer/src/FieldPlayer.cpp
Noticed that this is a problem, in the states where it's mean to freeze (ref positioning and pre execute) the search tasks still exist so the robot will not freeze if it's lost to ball or not localised.
This PR fixes that by checking for freezing first.
> Ensure the FieldPlayer freezes when referee positioning for penalties

- module/skill/Walk/data/config/Walk.yaml
Forgot to add this in the kick step PR.
> Add kick timing offset cfg to webots walk

- CMakeLists.txt
> Make NUSense the default subcontroller when building

- shared/utility/math/filter/YawFilter.hpp
This PR fixes an angle wrapping issue in the YawFilter
> Fix wrapping issue in YawFilter

- module/input/Camera/data/config/billie/Cameras/Left.yaml
- module/input/Camera/data/config/frankie/Cameras/Left.yaml
- module/input/Camera/data/config/kevin/Cameras/Left.yaml
- module/input/Camera/data/config/sarah/Cameras/Left.yaml
Frankie's params were very out when I was running during the practice game. 
Also remembered `auto` worked better for the FOV when @WongAaronSW was having a look the other weekend. It straightens out the lines a bit.
> Tune Frankie's camera pitch and change all FOV to auto

- module/skill/GetUp/src/GetUp.cpp
- shared/utility/math/filter/YawFilter.hpp
This PR adds an emit to indicate to rest of system that the robot is fallen when getting up.
> Emit fallen stability message when fallen and getting up

- module/strategy/FallRecovery/src/FallRecovery.cpp
Disable falling relax temporarily until freezing issue is fixed.
> TEMP: Disable falling relax

- module/purpose/Attack/data/config/Attack.yaml
- module/purpose/Attack/src/Attack.cpp
- module/purpose/Attack/src/Attack.hpp
This PR
- Makes whether to kick or not configurable, for quick changes
- Adds in functionality to kick only in attacking third, which is set in this PR
> Makes when we kick configurable and sets to attacking third

- module/localisation/FieldLocalisationNLopt/src/FieldLocalisationNLopt.cpp
The one removed in this PR has bad data and causes the graph to just look like extreme oscillations.
> Remove the double log in field localisation

- module/tools/RoboCupConfiguration/data/config/RoboCupConfiguration.yaml
Hopefully they don't change, tested and works.
> Update the SSID and passwords

- module/skill/Walk/data/config/sarah/Walk.yaml
- module/vision/GreenHorizonDetector/data/config/GreenHorizonDetector.yaml
- module/vision/Yolo/data/config/Yolo.yaml
Sarah has a dodgy walk (unknown why).
Yolo change to cut out some erroneous x's.
Green horizon higher confidence to try to cut out field line points outside the boundary.
> Walk and vision tuning [RoboCup]

- module/vision/FieldLineDetector/data/config/FieldLineDetector.yaml
- module/vision/FieldLineDetector/src/FieldLineDetector.cpp
- module/vision/FieldLineDetector/src/FieldLineDetector.hpp
Checked on robot and webots. Looks fine.
> Cut out field lines at a distance [RoboCup]

- module/input/GameController/src/GameController.cpp
- module/input/GameController/src/GameController.hpp
This fixes the issue where we don't show as green when connected on the new GameController.
> Change from using broadcast to unicast for GameController reply packets

- module/skill/Walk/data/config/Walk.yaml
- module/skill/Walk/data/config/sarah/Walk.yaml
- module/skill/Walk/data/config/webots/Walk.yaml
- module/skill/Walk/src/Walk.cpp
- shared/utility/skill/WalkGenerator.hpp
Add ability to tune starting torso sway
> Add ability to tune starting torso sway

- module/tools/RoboCupConfiguration/data/config/RoboCupConfiguration.yaml
- module/tools/RoboCupConfiguration/src/RoboCupConfiguration.hpp
Now that we have the official SSIDs and IPs. Drop ins have changed to 98 and 99.
> Update the SSIDs and DropIn team ID/IP

- module/strategy/FindObject/src/FindObject.cpp
I think this was my bad with the search changes.
> Fix head look around during search

- roles/robocup.role
Runs fine, shouldn't be an issue outside of drop ins as long as the opponent doesn't spam RoboCup packets.
> Add robot communication back in

- module/extension/Director/src/director/remove_task.cpp
- module/extension/Director/src/director/run_task_pack.cpp
> Stop double waits in the Director and fix cleanup in the tree causing orphans trying to run tasks

- module/localisation/RobotLocalisation/src/RobotLocalisation.cpp
Pretty sure this is a problem and causing the team to have two attackers. Listen to our friends!
> Don't ignore high localisation cost teammates

- module/extension/Director/src/director/run_task_pack.cpp
> Add director wait stuff

- module/purpose/FieldPlayer/src/FieldPlayer.cpp
- module/purpose/ReadyAttack/data/config/ReadyAttack.yaml
- module/purpose/ReadyAttack/src/ReadyAttack.cpp
- shared/utility/strategy/positioning.hpp
I think the ball moving logic is probably fine still, but maybe safer to remove. The real issues was likely the bug in the vector positions.
> Fix the kick off positioning values and dont trigger play when the ball moves

- module/input/GameController/src/GameController.cpp
- module/purpose/Soccer/data/config/Soccer.yaml
- module/purpose/Soccer/src/Soccer.cpp
- module/purpose/Soccer/src/Soccer.hpp
- shared/message/input/GameState.proto
Adds goalie info to the GameState message and uses it instead of a config variable in the Soccer module.
> Use game controller state to determine goalie

- module/extension/Director/src/director/emit_state.cpp
- module/extension/Director/src/director/run_task_pack.cpp
- nusight2/src/client/components/director/components/graph_view.tsx
- nusight2/src/client/components/director/components/provider_group_view.tsx
- nusight2/src/client/components/director/model.ts
The Director view shows "Unamed" for wait tasks, this changes it so it shows the correct name.
Also it was converting to relative time and back for actually waiting, so this changes that to use absolute times instead.
> Make the Wait task be named properly and change the wait to use absolute time

- module/tools/RoboCupConfiguration/data/config/RoboCupConfiguration.yaml
- module/tools/RoboCupConfiguration/src/RoboCupConfiguration.hpp
Although drop ins may not exist in the new league.
> Adjust for the new drop in IDs being 98 and 99

- module/input/Camera/data/config/Cameras/Left.yaml
- module/input/Camera/data/config/billie/Cameras/Left.yaml
- module/input/Camera/data/config/frankie/Cameras/Left.yaml
- module/input/Camera/data/config/kevin/Cameras/Left.yaml
- module/input/Camera/data/config/sarah/Cameras/Left.yaml
- module/input/Camera/src/Camera.cpp
Add yaw option when tuning extrinsics
> Add yaw option when tuning extrinsics
