Vagrantfile, puppet/modules/build_tools/manifests/init.pp
System-level protobuf requires zlib, but no zlib was being installed.
Vagrantfile also incorporates the troubleshooting commands that @JakeFountain  added to the readme. This addition will cause these troubleshooting commands to run every time `vagrant up` or `vagrant reload` is run.
=> Adds missing zlib dependency to build vm.

.gitattributes, .travis/build_code.sh, b, tools/platform.py
Windows users often pull with \r\n line endings. This breaks all the bash scripts and the b script since bash interprets it to start with.
This PR forces git to pull using newlines.
=> Fix issues so that b works on windows

.gitattributes
adds backwards compatibility with git.
=> Ignore line endings on binary files

README.md
Currently the travis badge says failed a lot because of other PRs that failed. The badge on master should reflect master.
=> Fix the travis icon to show the status of master.

shared/utility/ConfigureUtilities.cmake
NUtilities message outputs default to warnings so they show up when you ccmake.
This sets them to statuses so they dont.
=> Stop NUtilities printing messages on ccmake

.travis/install_toolchain.sh, module/support/configuration/NetworkConfiguration/src/NetworkConfiguration.cpp, puppet/manifests/nubots.pp, puppet/modules/toolchain_deb/files/control
New NUClear networking supports unicast and broadcast networks which will work better when there is no default route to send multicast packets on.
=> Upgrade to new version of NUClear which will support better networking

shared/utility/math/matrix/Transform3D.h
Resolves issue #18 
This is to handle the case where (A * B).i() should use the affine inverse for homogeneous matrices if both A and B are Transform3D. If B is not a Transform3D then default to the generic inverse calculation.
=> Overloads operator* for Transform3D

module/input/Camera/src/Camera.h, shared/utility/vision/Vision.h
Aravis is a C library and it should be treated as such
=> Suppresses "ISO C++ forbids flexible array member" warnings

shared/extension/Script.h
GCC is confusing the `NUClear::extension` namespace for these which prevents compilation
=> Fix scripts compile error

module/support/configuration/GlobalConfig/data/config/GlobalConfig.yaml
This updates the `teamId` in `GlobalConfig.yaml` for RoboCup 2019.
New team ID is 23, from https://github.com/RoboCup-Humanoid-TC/GameController/commit/7af05c7c0a01e2755fd5e930f57263108035cd2e#diff-0289f5237e915741aec10411f9bbacbeR8
This was tested and works with the Game Controller.
=> Update team ID for RoboCup 2019

module/behaviour/planning/SimpleWalkPathPlanner/src/SimpleWalkPathPlanner.cpp, module/input/Camera/src/AravisCamera.cpp
Please check if this breaks your robot. We had issues where cameras stopped sending images after some timeouts, after close investigation, the camera was running out of buffers to insert images.
=> Fix Aravis Buffer on Invalid Image from Camera.

.devcontainer.json, .vscode/extensions.json
Update the extensions as they no longer exist, 1 was moved to Microsoft and the other which was a bridge is now redundant because it's built into the main extension
=> Update the cmake extensions that were taken over by microsoft

module/platform/darwin/HardwareSimulator/src/HardwareSimulator.cpp, roles/keyboardwalkfake.role
Hardware simulator had errors. Was never picked up in GitHub since no roles used hardware simulator. Added `keyboardwalkfake.role`, which uses hardware simulator, to test.
=> Fixes hardware simulator

.buildkite/pipeline.yml
Split the docker image pushing so it goes to multiple agents, this should help improve time for image pushing
=> Split up the docker image pushing to multiple agents

docker/.dockerignore, docker/Dockerfile
This PR prevents Arch Linux from updating any packages and forces all images to maintain version compatibility for all installed packages.
=> Force Arch Linux to remain at a fixed date in the Docker image

tools/dockerise/__init__.py
The current `run_in_docker()` implementation detects if it's running in WSL and translates the source bind path to a WSL path. This doesn't works in WSL 2, and causes the mount to fail; leading to this error when running the `b` script:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./b\": stat ./b: no such file or directory": unknown.
```
This PR ensures that the path translation is done only in WSL 1.
=> Fix Docker mount error in WSL 2

tools/nbs/filter.py, tools/nbs/nbs/encoder.py
This tool will allow you to take an nbs file, and filter out specific message types from it. This can be useful for example if you have an NBS file with images/sensors in it but don't want to carry around a gigantic file. You could strip out the image messages and just keep the sensor data.
=> Add a tool for filtering out message types from nbs files

tools/dockerise/__init__.py
Currently, if you are not the first user on your computer (your UID is not 1000) then when you run in your docker image you'll get permissions errors. This sets the user id to the same as your current user when generating images.
=> Make dockerise copy over the current users UID to avoid permissions errors

tools/dockerise/__init__.py
Pairs with https://github.com/NUbots/NUsight2/pull/335.
This allows for connecting the container to a custom docker network, for communication with NUsight when it's run in a container.
A custom network for the containers can be created like so:
```sh
docker network create nuclearnet
```
And usage of `./b run` can be adjusted like so:
```sh
./b run keyboardwalkfake --network nuclearnet
```
This is the only way to get the two to talk on Windows when NUbots is running in a container: run NUsight in a container too, and connect both containers to the same Docker network.
The other options:
- `host` networking (the current default): [not available on Windows](https://docs.docker.com/network/network-tutorial-host/#prerequisites), though it works on Linux ~(and probably macOS too)~
- `bridge` …
=> Allow passing container network as arg to `./b run`

shared/tests/utility/motion/TestSplines.cpp
The SmoothSpline unit test was incorrect because time values were not consecutive.
The error was not picked up because the test failed rarely. It failed rarely because the allowable error was (incorrectly) too large. A missing negative sign gave an error threshold of 1,000,000 instead of 0.000001 :grimacing: 
This PR fixes both the error threshold and the issue with consecutive time values.
=> Fix the SmoothSpline unit test.

nuclear/message/include/message/conversion/proto_matrix.hpp
The object was reserved meaning that there was enough space to copy over, however, the size was not updated resulting in protobuf not serializing any bytes
=> Fix bug in proto_matrix.hpp where memory was not resized properly

docker/Dockerfile
Fixes linking errors when building `ocl-icd` a bit later.
Fix verfied by @JosephusPaye  - I am having certificate issues for github related domains when building packages after that one atm, so I haven't been able to build the full image myself.
=> Pins version of OpenCL to fix linker errors

nuclear/b.py
Prepends our tools directories to the path, so that our tools are used first if there is a namespace conflict
=> Changes path to prefer our tools

tools/dockerise/__init__.py
Don't name the container, it means you can't run multiple ./b things at once (e.g. if you're in a ./b shell in one terminal you can't ./b build in another etc)
=> Remove the name from the container

doc/ArchInstall/arch_install.sh
wget has been removed from newer arch iso's, so we have to use curl for this instance. The NUbook arch flash guide will have to change too.
=> Removes `wget` from first arch install script

module/behaviour/Controller/src/Controller.cpp, module/behaviour/planning/BezierWalkPathPlanner/src/BezierWalkPathPlanner.cpp, module/behaviour/planning/SimpleWalkPathPlanner/src/SimpleWalkPathPlanner.cpp, module/behaviour/skills/DirectWalkController/src/DirectWalkController.cpp, module/behaviour/skills/FallingRelax/src/FallingRelax.cpp, module/behaviour/skills/Getup/src/Getup.cpp, module/behaviour/skills/GoalSaver/src/GoalSaver.cpp, module/behaviour/skills/KickScript/src/KickScript.cpp, module/behaviour/skills/Nod/src/Nod.cpp, module/behaviour/skills/WalkEngineStand/src/WalkEngineStand.cpp, module/behaviour/skills/WalkPathFollower/src/WalkPathFollower.cpp, module/motion/IKKick/src/IKKick.cpp, module/motion/OldWalkEngine/src/OldWalkEngine.cpp, module/support/NUsight/src/Subsumption.cpp, nusight2/src/shared/proto/message/behaviour/Subsumption.proto, shared/message/behaviour/Subsumption.proto, shared/utility/behaviour/Action.hpp
The name of this message is typo'd in master. This PR corrects the typo.
It builds, which I think is sufficient to say that it doesn't break anything?
=> Fixes typo in ActionPriorities message name.

module/behaviour/planning/KickPlanner/src/KickPlanner.cpp, module/behaviour/planning/SimpleWalkPathPlanner/src/SimpleWalkPathPlanner.cpp, module/localisation/BallLocalisation/src/BallModel.hpp, module/localisation/RobotParticleLocalisation/src/RobotModel.hpp, module/motion/IKKick/src/IKKick.cpp
On reading the eigen docs ([see the "Affine transformations" heading on this page](https://eigen.tuxfamily.org/dox/group__TutorialGeometry.html)), I have realised that there's no need to append a `1` to transform 3D vectors as points with eigen's affine transforms. Doing that makes the code harder to read and follow, and does nothing.
This PR cleans up the instances where I did exactly that.
=> Cleans up calls which were .transformPoint(arma::vec3) in the arma era

module/platform/darwin/HardwareIO/src/Convert.hpp
This adds more comments explaining the factors, as well as changing the speed conversion
The speed conversion factor was set for old servo models. This updates it with the values appropriate for the MX64/106, which are fortunately the same as each other
=> Updates CM740 Sensor Conversion

docker/Dockerfile
To run yarn and node stuff inside the container (as is done in `./b format`, for example), we need the node stuff
=> Adds NUsight's dependencies to the dockerfile

nusight2/package.json, nusight2/yarn.lock
There are some compiler warnings from the NUClearNet source, but it works.
=> Upgrade NUClearNet.js to 1.5.5

module/platform/Webots/src/Webots.cpp
We don't want to use both cameras because then we go over the bandwidth limit for RoboCup.
=> Only want to use one camera in Webots

module/platform/Webots/src/Webots.cpp, module/platform/Webots/src/Webots.hpp
At the moment we don't set a max bound, which results in webots being sent ridiculous velocity requests. This gives the simulator warnings. We don't want a load of warnings in the simulator console (particularly not in official games!). This PR fixes this so we have a bound.
=> Set a max bound on the velocity we send to webots

module/behaviour/skills/Getup/src/Getup.cpp, module/motion/ScriptEngine/data/scripts/docker/KickLeft.yaml, module/motion/ScriptEngine/data/scripts/docker/KickRight.yaml, module/motion/ScriptEngine/data/scripts/docker/StandUpBack.yaml, module/motion/ScriptEngine/data/scripts/docker/StandUpFront.yaml, module/motion/ScriptEngine/data/scripts/nugus/KickLeft.yaml, module/motion/ScriptEngine/data/scripts/webots/KickLeft.yaml, module/motion/ScriptEngine/data/scripts/webots/KickRight.yaml, module/motion/ScriptEngine/data/scripts/webots/NodYes.yaml, module/motion/ScriptEngine/data/scripts/webots/Relax.yaml, module/motion/ScriptEngine/data/scripts/webots/RelaxHead.yaml, module/motion/ScriptEngine/data/scripts/webots/RollOverFront.yaml, module/motion/ScriptEngine/data/scripts/webots/Stand.yaml, module/motion/ScriptEngine/data/scripts/webots/StandUpBack.yaml, module/motion/ScriptEngine/data/scripts/webots/StandUpFront.yaml, module/motion/ScriptEngine/data/scripts/webots/Zombie.yaml, roles/scripttuner.role, roles/webots_keyboard.role
This creates a folder for scripts for `webots#` robots. The scripts are tuned to work for the NUgus in Webots.
- `StandUpFront.yaml`
- `StandUpBack.yaml`
- `KickLeft.yaml`
- `KickRight.yaml`
It also updates from using the roll over method for getting up to just using either front or back get up.
When this is run normally (outside of RoboCup), the robot is `docker`, so those files are also updated. (Do we want to somehow make it use the `webots` folder when using webots?)
=> Create motion scripts to use in Webots

module/platform/Webots/data/config/webots.yaml, module/platform/Webots/src/Webots.cpp, module/support/configuration/GlobalConfig/data/config/GlobalConfig.yaml
The welcome message was read in as 7 bytes, but 8 bytes were associated with the message. One byte left over messed with the rest of communication. This fixed that.
It also updates the config so that we are using the right team id (as from GameController) and the right host IP address.
=> Fix communication in the Webots module to successfully connect to the official RoboCup controller

.gitignore
We're tracking a log file and this makes it stopped being tracked.
=> Stop tracking the log file

module/motion/ScriptEngine/data/scripts/docker/StandUpBack.yaml, module/motion/ScriptEngine/data/scripts/docker/StandUpFront.yaml, module/motion/ScriptEngine/data/scripts/webots/StandUpBack.yaml, module/motion/ScriptEngine/data/scripts/webots/StandUpFront.yaml
Turns out we weren't tuning on the exact field used in the RoboCup world (see NUbots/NUWebots#77). This updates the get ups so they work on the right field.
=> Updates the get ups for Webots

module/behaviour/skills/Getup/src/Getup.cpp
Before, we were disabling the reaction so it never got new sensor readings until it finished the script/s. Because of the averaging of the last 20 sensors, it was still using readings from when it first fell down. This caused a loop of trying to get up even when it was stood up again. 
This PR stops the reaction being disabled. Existing checks already make sure the robot doesn't get up again when trying to get up. 
Tested in Webots with the official RoboCup controller, and works.
=> Fix the get up so that we don't keep trying to get up

module/platform/Webots/src/Webots.cpp
When we communicate with Webots, we create a buffer that holds the data we read. When we have enough data to create a sensor measurements protobuf message, we create that message and then erase those bytes from the buffer. Just before erasing the data, the connection would sometimes disconnect and clear the buffer. This resulted in trying to erase data from a buffer with nothing in it. 
This PR adds the `Sync` DSL word to the `read_io` and `Watchdog` reactors to prevent this race condition.
=> Fixes the race condition when reconnecting in the Webots module

module/motion/QuinticWalk/src/QuinticWalk.cpp, module/motion/QuinticWalk/src/WalkEngine.cpp, module/motion/QuinticWalk/src/WalkEngine.hpp, shared/utility/motion/splines/TrajectoryUtils.hpp
~`computeCartesianPosition[AtTime]` takes a boolean parameter `isLeftsupportFoot` (passed by value), which is then passed to `TrajectoriesSupportFootState`, which modifies the value as a reference. The call to that function does nothing because the bool is passed by value into the previous function call (this is the only use of `TrajectoriesSupportFootState`).~
~This changes it to be passed by reference, which is certainly the intention~
Update:
I have made the trajectoryutils functions return a tuple instead of mutating its parameters. This is much nicer
=> Changes return types of walk engine functions which mutated many references

shared/extension/Configuration.hpp
Yaml-cpp has some overloads that let you set a default for .as calls.
This forwards arguments using perfect forwarding to yaml-cpp so it can use them
=> Upgrade configuration `.as<>` so it can use yaml-cpp overloads

docker/nugus_sim/run.py
Restart binary if it crashes instead of stopping the container.
=> Make robocup container uncrashable

tools/run.py
if the file `$NUBOTS_HOME/log` existed, and it wasn't a directory, an exception is thrown, and the script exits. This change catches the exception, and moves that existing log into the new log directory
=> Fixes FileExists exception caused by the log file not being a directory

tools/webots.py
Forgot default value for `clean` when using `./b webots run`
=> Fix webots run

module/support/logging/DataLogging/data/config/webotsrobocup/DataLogging.yaml
This turns of logging off `CompressedImage`, `VisualMesh`, and `GreenHorizon` messages in the webotsrobocup role. This is needed to not exceed the 10GB per robot limit, which we've exceeded so far in our first few games.
=> Reduce logging in the `webotsrobocup` role

module/platform/darwin/HardwareSimulator/src/HardwareSimulator.cpp
Changes to localisation mean that the accelerometer z axis of hardware simulator no longer needs to be flipped. Robot thinks it is upside down
=> Update accelerometer z axis to positive value

module/platform/darwin/HardwareSimulator/src/HardwareSimulator.cpp, module/platform/darwin/HardwareSimulator/src/HardwareSimulator.hpp
At the moment, hardware simulator has a mechanism for handling gyroscope data using a queue of gyro readings. However, (I am reasonably sure) that nothing emits gyro readings. 
If they were emitted, we think the code would break because as @Bidski  pointed out to me, if it was executed, it would attempt to acquire the same mutex twice in a row.
This PR removes that stuff which handles gyroscope readings in hardware simulator. We might want to fix it instead, in which case I am happy to close this PR, but I figure it might as well go if we used it this long without that function anyway lol
=> Removes gyro stuff from hardware simulator

module/motion/QuinticWalk/src/WalkEngine.cpp
I found these logs more confusing than they needed to be. This PR punctuates them, making them clearer IMO
=> Gives Walk Engine logs punctuation for readability

module/behaviour/skills/Getup/src/Getup.cpp, module/input/SensorFilter/src/SensorFilter.cpp, module/platform/Gazebo/src/Gazebo.cpp, module/platform/Webots/src/Webots.cpp, module/platform/darwin/HardwareIO/src/HardwareIO.cpp, module/platform/darwin/HardwareSimulator/data/config/DarwinHardwareSimulator.yaml, module/platform/darwin/HardwareSimulator/src/HardwareSimulator.cpp, module/platform/darwin/HardwareSimulator/src/HardwareSimulator.hpp, shared/message/platform/RawSensors.proto
`RawSensors::{Accelerometer, Gyroscope}` are both message types wrapping vectors. Now that we have nice vector types in proto + neutrons, these are unnecessary. 
This PR removes those message types and changes the code where they were used.
=> Refactors vector style messages into vectors

.github/dependabot.yml
I went through the config options and selected the ones that seem relevant.
This will assign the members of the `nusight` group to review the PRs dependabot makes.
=> Adds dependabot config file

docker/nugus_sim/run.py
Adds some debugging statements to nugus_sim entrypoint, specifically for finding out if our binary crashed.
=> Add debug statments to nugus_sim image entrypoint

tools/utility/dockerise/run.py
If vscode has created a container then deleting the build volume will because the volume is in use. Deleting the vscode container is undesirable as vscode installs extensions. etc in this container and they can take a while to download.
This PR removes the "delete build volume on clean" behaviour and replaces it with a "delete all files/folder in build volume" behaviour.
=> Purge build volume files rather than re-creating it

module/behaviour/skills/Getup/src/Getup.cpp, module/behaviour/skills/Getup/src/Getup.hpp
This PR removes the ReactionHandles in Getup to prevent a race condition that resulted in Getup taking control and never giving it up. 
The problem was
- Get up is detected, priority is increased :arrow_up: 
- Because priority is increased, Getup gets control and ExecuteGetup is emitted :envelope: 
- getUp reactor is enabled by default so it runs fine :+1: 
- KillGetup runs after get up finishes and disables the getUp reactor :x: 
- Get up is detected, priority is increased :arrow_up: 
- Because priority is increased, Getup gets control and ExecuteGetup is emitted :envelope: 
- getUp reactor was disabled, so it doesn't run :x: 
- getUp reactor is enabled, but ExecuteGetup has already disappeared :cry:
=> Stops the robot from freezing after trying to get up twice

module/motion/QuinticWalk/src/QuinticWalk.cpp
It casts to a matrix of doubles, before immediately casting back to floats. This is silly
=> Removes unnecessary casts from QuinticWalk reaction

nusight2/docker-compose.yml
Currently, the [`generate_messages.js`](https://github.com/NUbots/NUbots/blob/main/nusight2/build_scripts/generate_messages.js) script can't find the proto files in the docker container, since only the `nusight2`folder is mounted. This mounts the top-level NUbots folder as well, which fixes the issue.
The change to mono repo broke the script and we didn't notice.
=> Fix the NUsight docker container

module/behaviour/planning/SimpleWalkPathPlanner/src/SimpleWalkPathPlanner.cpp, module/behaviour/planning/SimpleWalkPathPlanner/src/SimpleWalkPathPlanner.hpp
Updated SimpleWalkPathPlanner to use a switch case and a couple of void utility functions to tidy up the code and make it simpler to make changes to the behavior of the path planning at a higher level. I also added some extra content and documentation hooks.
I expect I've made a few mistakes or implemented it incorrectly, please let me know here so I can fix them up and learn best practices. Thanks!
=> Update SimpleWalkPathPlanner into a switch case and functions

module/input/SensorFilter/src/SensorFilter.cpp
**Add clearing of filtered_sensors after each loop in sensor filter**
filtered sensors was not cleared after each loop through the sensors when resetting the sensor filter. This makes sure it is cleared after using it to calculate forward kinematics and averages on a iteration
=> Add clearing of filtered_sensors after each loop

docker/nugus_sim/run.py, tools/webots.py
- Update the ECR URL with the one provided by TC
- Only set `ROBOCUP_TEAM_ID` env var if it is provided
=> Update robocup ecr url and set env vars correctly

docker/Dockerfile.nugus_sim
In #779 `etc/pacman/pacman.latest.conf` and `/etc/pacman.latest.conf` were added in the Docker container to be used by `install_script` when updating keys. 
`install_script` is also used by `Dockerfile.nugus_sim`. `Dockerfile.nugus_sim` wasn't changed to add the previously mentioned config files.
This results in an error when building because it can't find the config file.
Adding in the copy line results in a successful build.
=> Add pacman config to the sim Dockerfile

shared/clock/clock.cpp
The real robot cannot walk properly on the main branch. The clock change from RoboCup has broken the walk. The walk uses the difference between now and the last time update, but this difference was becoming increasingly large over time until after around 1-2 seconds it was too large and the QuinticWalk refuses to do anything more. 
The problem is that there is a race condition in the clock. I put in a mutex and now it's working on the real robot.
I've checked Webots and its still working fine there too.
=> Add a mutex to the clock to prevent race condition

CMakeLists.txt, module/behaviour/tools/ScriptTuner/src/ScriptTuner.cpp
**Why are you updating?**
Because I want to use atomic pointers in #807. [Atomic shared_ptr](https://en.cppreference.com/w/cpp/memory/shared_ptr/atomic2) is only available in C++20.
**Why did you change script tuner?**
Because 
```
implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
```
=> Update the codebase to C++20

.github/dependabot.yml
Dependabot currently spams PRs to update NUsight dependencies. This turns off Dependabot for NUsight dependencies, but keeps GitHub Actions. 
Reasons for turning it off
- Clutters the PRs list since there are a lot of dependencies
- We don't do anything with the PRs
=> Remove NUsight Dependabot

doc/Kinematics/Export_Step.py, docker/Dockerfile, nuclear/roles/banner/ampscii.py, report/graph/build_role_graph.py, report/graph/info/symbol_parser.py
Bump the zlib version from `1.2.11` to `1.2.12` as the old version is no longer hosted, preventing the docker build.
Bump the black version as they pin `click>=7.0` but that had breaking changes in `8.1`, which was fixed in a later black version.
=> Bump zlib and black versions

module/vision/VisualMesh/src/visualmesh/VisualMeshRunner.cpp
Issue was that the real robot was constantly giving no mesh points on screen error, no matter what angle it was at (pitch and roll work ok on the real robot). 
Making this change fixed it so it'll draw the mesh on the ground.
=> Fix for vision on the real robot: update calculation for k before used in Visual Mesh

doc/ArchInstall/arch-chroot_install.sh
Old line was out of date, it tried to uncomment something that used to be there but now is slightly different.
This PR makes a new file in the `etc/sudoers.d/` directory with the right line.
The purpose is to grant sudo access (without requiring a password) to anyone in the wheel group. `nubots` is in the wheel group.
=> Fix out of date sudoers line in arch install script for the robot

module/input/SensorFilter/data/config/webots/SensorFilter.yaml, module/motion/QuinticWalk/data/config/webots/QuinticWalk.yaml, module/vision/VisualMesh/data/config/VisualMesh.yaml, module/vision/VisualMesh/data/config/nugus/VisualMesh.yaml, module/vision/VisualMesh/data/config/webots/VisualMesh.yaml, shared/extension/Configuration.hpp, tools/utility/dockerise/run.py
- Updates the Configuration extension to allow platform-specific configuration files
- Update the docker run command to use 'webots' as the hostname if the user is using `./b run` and their binary contains the word `webots`
- Updates the QuinticWalk config - in Webots, the default config was used and there was no way to run with the config in the already-existing QuinticWalk `webots` config directory. With these changes, the Webots platform should run with the config file in the QuinticWalk `webots` config directory. Updates this config to the same values as the default config so the webots robot will use the right values.
- Added two platform config files for the visualmesh module, one for the nugus and one for webots. The default file only contains the log level, since each platform …
=> Add in platform-specific configuration and set the hostname in docker to 'webots' if the role contains the word 'webots'

module/input/Camera/data/config/nugus2/Cameras/Left.yaml, module/input/Camera/data/config/nugus2/Cameras/Right.yaml, module/input/Camera/data/config/nugus3/Cameras/Left.yaml, module/input/Camera/data/config/nugus3/Cameras/Right.yaml
The nucs were swapped around in the nugus' earlier this year. Camera config needs to be swapped around to the right nugus'. They have already had serial numbers checked and calibration performed.
=> Switch around nugus2 and nugus3 Camera config files after nuc swap

tools/utility/shell/wrap_pty.py
This PR prevents your terminal from going insane after running a `./b` command by
- overriding signal more signal handlers
- resetting TTY (terminal) settings when a signal is caught or when the script ends
=> Always restore tty settings

module/behaviour/skills/KickScript/README.md, module/behaviour/skills/KickScript/data/config/KickScript.yaml, module/behaviour/skills/KickScript/src/KickScript.cpp, module/behaviour/skills/KickScript/src/KickScript.hpp, roles/webots_keyboard.role
Alternative to #842.
- Adds Stand module to `webots_keyboardwalk.role` inline with other motion roles
- Makes kick priority lower than get up priority
- Uses shared pointer to check kick command exists
- Adds a timeout so that the kick isn't executed too long after a kick command (since we probably are no longer necessarily in a good position to kick)
- Fill in module readme
- Add document directives
=> Stop extra kick in webots_keyboardwalk and add in a kick timeout

module/behaviour/skills/Getup/src/Getup.cpp, module/motion/ScriptEngine/data/scripts/nugus/RollOverBack.yaml, module/motion/ScriptEngine/data/scripts/nugus1/StandUpFront.yaml
- Changed due to metal legs not quite managing to stand up from it's back. That's another issue that is being sorted.
- This will effect all robots as they will all have metal legs pretty soon.
- Adds RollOverBack.yaml
- Updates behaviour
- Evened out shoulder roll on stand up script
=> Replaces stand up back with rollover/stand up front

module/platform/cm740/HardwareIO/data/config/nugus3/HardwareIO.yaml
Adjusted HardwareIO for nugus3's metal legs. Took out the minor difference needed to account for manufacturing faults in nugus1.
=> Adds HardwareIO for nugus3's metal legs

.Doxyfile
We currently include all source files in the codebase for Doxygen. I feel its better if we stick to only the files in `shared` and `module` so as not to include the more obscure types in the documentation.
=> Only include primary source files in Doxygen

module/output/ImageCompressor/data/config/ImageCompressor.yaml, module/output/ImageCompressor/data/config/nugus/ImageCompressor.yaml, module/output/ImageCompressor/data/config/webots/ImageCompressor.yaml
Webots uses turbojpeg to compress images, but the robot should use vaapi since it's set up for it and it's quicker. During RoboCup 2021, we changed the default config for ImageCompressor to use turbojpeg because this is what we needed for webots. This PR creates platform specific config for ImageCompressor so that webots will use turbojpeg and the robot will use vaapi.
This was mostly discovered due to a current memory leak in turbojpeg on the real robot, which should be fixed in a follow up PR. See #868.
=> Make webots and nugus specific image compressor config

docker/Dockerfile
OpenCL caching on the old commit.
Webots breaks with latest visual mesh code.
=> Uses old visual mesh commit with opencl cashing on top

module/extension/Director/src/Director.cpp, module/extension/Director/src/Director.hpp, module/extension/Director/src/information/get_task_data.cpp, shared/extension/Behaviour.hpp, shared/extension/behaviour/InformationSource.cpp, shared/extension/behaviour/InformationSource.hpp
This adds an InformationSource class interface that lets the Behaviour DSL communicate with the Director so they can provide information about the task that is running
=> Add an information source so the Director can communicate to the Behaviour DSL

module/support/configuration/GlobalConfig/data/config/GlobalConfig.yaml, module/support/configuration/GlobalConfig/data/config/darwin1/GlobalConfig.yaml, module/support/configuration/GlobalConfig/data/config/darwin2/GlobalConfig.yaml, module/support/configuration/GlobalConfig/data/config/darwin3/GlobalConfig.yaml, module/support/configuration/GlobalConfig/data/config/darwin4/GlobalConfig.yaml, module/support/configuration/GlobalConfig/data/config/darwin5/GlobalConfig.yaml, module/support/configuration/GlobalConfig/data/config/darwin6/GlobalConfig.yaml
Removes the Darwin config, since it's not really needed.
Updates the default team ID to the team ID for 2022. This will be useful during practice games until next competition.
=> Remove Darwin Global Config and Update Default for 2022

module/behaviour/planning/SimpleWalkPathPlanner/src/SimpleWalkPathPlanner.cpp
`robocup` on `main` is broken, the robot won't walk because SimpleWalkPathPlanner expects a `WantsToKick` message and it never gets one. It came from KickPlanner, but we don't use it anymore and it was removed from the role at some point.
=> Remove wants to kick from walk path planner

nusight2/src/client/components/vision/camera/styles.css, nusight2/src/client/components/vision/camera/view.tsx
No more "which one is the left camera?" This PR updates vision to show the camera name on each image.
=> Show camera name on images in NUsight

nusight2/conf/storybook/webpack.config.ts
Currently a failed webpack build of Storybook (due to a syntax error for example) shows no details about where the error is. This PR makes it show the source of the errors.
<details>
<summary>Before (with a syntax error)</summary>
</details>
<details>
<summary>After (with a syntax error)</summary>
</details>
=> Show error details when NUsight Storybook build fails

shared/extension/Configuration.hpp
https://github.com/NUbots/NUbots/actions/runs/3216813323/jobs/5259088665#step:7:110
This failed because no platform, I guess a GitHub actions thing? Anyway this allows for no platforms by returning an empty string and checking for empty around the place. Tested on https://github.com/NUbots/NUbots/pull/963 and it seems to work :shrug:
=> Allow empty platforms in Configuration extension

module/extension/Director/src/director/run_task_pack.cpp, module/extension/Director/tests/idle.cpp, shared/extension/Behaviour.hpp
This PR adds a new Idle word to the director.
This is so that it can choose to not update the subtasks it emitted last time.
The eventual intention for this is to work with the upcoming done information that will inform providers which of their subtasks emitted a "done" task.
Also fixes a few minor bugs that I noticed while coding this
=> Add functionality so Director Providers can Idle

module/extension/Director/src/Director.cpp, module/extension/Director/src/Director.hpp, module/extension/Director/src/information/get_task_data.cpp
Sync isn't working to prevent multithreading issues, use a mutex. Use a recursive mutex because of `_get_task_data`, which also needs a mutex but can be called indirectly within Director reactions.
=> Use a recursive mutex in Director instead of Sync

module/extension/Director/src/director/challenge_priority.cpp, module/extension/Director/tests/challenge_child.cpp
`challenge_priority` function was broken, the ancestors were not right. This prevented a parent task from beating its child in the `challenge_priority` function. This PR adds a test for that case and fixes the function.
=> Fix challenge priority function in Director and adds a test that targets the error

module/extension/Director/src/Director.cpp, module/extension/Director/src/Director.hpp, module/extension/Director/src/director/hold_run_reason.cpp, module/extension/Director/src/director/remove_task.cpp, module/extension/Director/src/director/run_task_on_provider.cpp, module/extension/Director/src/director/run_task_pack.cpp, module/extension/Director/src/information/get_run_info.cpp, module/extension/Director/tests/run_reason.cpp, shared/extension/Behaviour.hpp, shared/extension/behaviour/InformationSource.hpp
Adds an optional RunInfo object that can be given alongside a provider that can give additional information about why it was run.
Currently only provides an enum that describes the reason the provider was executed.
=> Add extra information so Director Providers can know why they were executed

module/extension/Director/src/Director.cpp, module/extension/Director/src/director/run_task_pack.cpp
By the time a task pack gets run, sometimes the provider is no longer active. Running the task pack breaks the tree. Need to check for this in `run_task_pack`.
=> Fix bug where Providers that are no longer active try to run subtasks

module/input/Camera/data/config/Cameras/Left.yaml, module/input/Camera/data/config/Cameras/Right.yaml
Change of plan from having a set exposure and trying to compensate for darker images with gain. Now sets an auto exposure upper limit to allow for some auto adjustment, and compensates somewhat by setting the grey value. Seems to work a bit better.
- Turned auto exposure back on and set an upper limit of 3000.
- Sets frame rate to 100.
- Turned off auto exposure grey target value and set to 30.
=> Updates default camera settings to compensate for motion blur

shared/extension/NewScript.hpp, shared/extension/behaviour/Script.hpp
Allows us to do
```cpp
emit<Script>(std::make_unique<LimbsSequence>(), "KickRight.yaml");
```
Then that'll load the script and emit a LimbsSequence for that script.
Future work: cache scripts
=> Add a Script extension that works with Director

shared/extension/behaviour/Script.hpp
For Director.
Changes the Script to take a vector of Scripts rather than one, and concats the scripts into one set of servo sequences.
Also some minor bug fixes.
Example of use:
`emit<Script>(std::make_unique<LimbsSequence>(),
std::vector<ScriptRequest>{{"KickLeft.yaml", 1.0}, {"KickRight.yaml", 1.0}});`
=> Changes Script extension to take a sequence of scripts

module/actuation/Servos/src/Servos.hpp
Fixes a bug that can occur when a servo group Task is made without all the servos in that group.
Mostly applicable to scripts. Makes it easier when running a sequence of scripts.
Ignores servos that don't exist in the message.
=> Director Servos (Group) Update - ignore missing servos in map

module/platform/Webots/data/config/WebotsCameras/left_camera.yaml
Two problems with the Webots camera config
- FOV was taken from Webots, which is horizontal FOV, but the config is for diagonal FOV, so this has been updated
- Hpc looks like it was copied from a calibrated robot camera, in this PR it has been changed based on the model and given that the cameras in webots are positioned without any extra rotation relative to the last joint, the rotation is identity.
Original is
and with this update we have
=> Update webots camera FOV and Hpc

docker/Dockerfile
Currently the Visual Mesh library we grab in the Dockerfile is from a commit on my personal fork. It's a pretty old version of the public Fastcode/VisualMesh repo but applies last year's OpenCL caching so we're not waiting forever for the engines to load.
This PR uses a commit (currently the latest) from the new NUbots fork of Fastcode/VisualMesh. The commit contains everything on the current Fastcode/VisualMesh repo but it applies two fixes
- Reverts a change in the CPU engine that breaks it (thus breaking Webots vision)
- Applies a fix for the holes that were appearing in the mesh, credit to @Bidski 
Overall the benefits of this PR are
- Using a NUbots fork instead of my personal one
- Adding a lot (like 10+) of recent(-ish) commits from Fastcode that hopefully have some benefits 
- No …
=> Bring the Visual Mesh more up to date with the Fastcode repo and fix the holes in the mesh

.gitignore, CMakeLists.txt, cmake/scripts/generate_launch_configurations.py
This PR will generate a `.vscode/launch.json` file containing a launch configuration for each role that is currently being built that will allow those roles to be actively debugged inside of VS Code.
There are a couple of limitations to this
1. This will only work inside the devcontainer
2. Since the devcontainer currently does not expose any GPUs, no roles/modules that use a GPU can be debugged in this manner, you will have to fallback to the ./b run --gpus all --gdb role/to/debug method
Have you
Pull this branch and run `./b configure` followed by `./b build`. One of the build targets will generate `.vscode/launch.json` which will contain a launch configuration for all of the currently built roles.
Now switch to the `Run and Debug` tab in VS Code (or `Ctrl+Shift+D`) and you will be able …
=> Add VS Code debugging launchers for roles

module/skill/Look/data/config/Look.yaml, module/skill/Look/src/Look.cpp, module/skill/Look/src/Look.hpp, roles/webots/directormotion.role, shared/message/skill/Look.proto
The PR makes the Look skill somewhat more accurate.
- Uses rPCt instead of rPCc
- Smooths the vector, not the angle (no conversion to angles in the Look skill)
The changes result in
- The head looks directly at the ball, rather than before where it was not quite accurately looking at the ball particularly on the bounds of the head angles
- There is an oscillation issue around IK problems but the smoothing stops most of the movement
=> Updates the Look skill to use torso space and vector for smoothing

tools/webots.py
The script accepts a role name as command line input. It searches all the role files and checks if the requested role exists.
The old role search found the full path of the roles. This means the script fails to find the role in the available list. If you input the full path, then the part where the script turns the role on and builds it fails because it expects the role path and name relative to the role folder. 
This PR fixes it so the role search stores the role names relative to the folder and without the `.role` suffix. 
Also changed the image tag from robocup2021 to robocup.
=> Fix the role search in the Webots build command for the virtual competitions

module/planning/PlanLook/README.md, module/planning/PlanLook/data/config/PlanLook.yaml, module/planning/PlanLook/src/PlanLook.cpp, module/planning/PlanLook/src/PlanLook.hpp, module/strategy/StrategiseLook/CMakeLists.txt, module/strategy/StrategiseLook/README.md, module/strategy/StrategiseLook/data/config/StrategiseLook.yaml, module/strategy/StrategiseLook/src/StrategiseLook.cpp, module/strategy/StrategiseLook/src/StrategiseLook.hpp, module/strategy/StrategiseLook/tests/StrategiseLook.cpp, roles/webots/directormotion.role, shared/message/planning/LookAround.proto, shared/message/strategy/LookAtFeature.proto
The planner includes only the LookAround (search).
The strategy includes the LookAtBall and LookAtGoals
This is to match better with the rest of the system, where WalkToBall is a strategy and TurnOnSpot is a planner.
The strategies only fixate on the ball/goals if they exist.
Future strategies will involve a FindBall which uses the LookAround and TurnOnSpot to find the ball.
A WalkToBall will only walk to the ball if the ball is found.
Then in the purpose level, if the WalkToBall and LookAtBall cannot run, the lower priority FindBall will take over and find the ball.
=> Refactor the Director Look planner into a planner and strategy

module/support/configuration/GlobalConfig/data/config/webots/GlobalConfig.yaml
We updated the team ID to 1 for last RoboCup, but there should still be a webots-specific configuration file with the team ID for the virtual games.
=> Add a webots global configuration file for the virtual season team ID

module/behaviour/skills/Getup/data/config/webots/Getup.yaml, module/behaviour/skills/Getup/src/Getup.cpp, module/behaviour/skills/Getup/src/Getup.hpp
There's no roll over script for webots so we get a runtime error with the current stuff. This fixes that by specifying separate scripts for webots and real.
=> Separate get up scripts into webots and real robot

module/strategy/WalkToBall/src/WalkToBall.cpp
There's a bug in the Director WalkToBall module. Had rBCc instead of rBTt.
=> Fix walk to ball bug in Director by changing space of measurement

module/planning/GetUpPlanner/src/GetUpPlanner.cpp, module/planning/GetUpPlanner/src/GetUpPlanner.hpp
Getup was made before the Uses RunState information was added, so it had a boolean to track if the getup was running. This updates it to use the Uses information instead. 
It also wasn't really working when I was testing some other stuff in the conversion from the old system and this works :shrug:
=> Update the getup module to use the RunState Uses information

module/planning/PlanLook/data/config/PlanLook.yaml
The look search was a bit slow. This quickens it up so it's more likely to see the ball near its feet when it's lost it.
=> Quickens the look search fixation time from 2 seconds to half a second

nusight2/src/client/components/localisation/controller.ts, nusight2/src/client/components/localisation/network.ts, nusight2/src/client/components/localisation/nugus_robot/view_model.ts, nusight2/src/client/components/localisation/robot_model.ts, nusight2/src/shared/math/quaternion.ts
Currently the localisation tab in NUsight doesn't show localisation. This PR fixes that!
It applies `message.localisation.Field.Hfw` to the robot's position.
Confirmed as matching the overview tab, which I'm assuming to be correct.
Attached is an nbs file recorded from running webots: [nbs_example.zip](https://github.com/NUbots/NUbots/files/11521928/nbs_example.zip)
=> NUsight localisation: Add world to field transformation

module/input/SensorFilter/src/SensorFilter.hpp
Issue appears specifically when running `webots/directorkeyboardwalk` and the robot has fallen, for some unknown reason. 
SensorFilter will crash with an Eigen cannot resize matrices error. 
Problem is that we're trying to give it `Bc` which is of size `n_inputs` by `n_inputs`, when it wants something of size n_states by n_inputs. Tbh n_inputs seems to be zero anyway.
Edit to add that there is still another bug making it crash (probably Director), but this happens first.
=> Fix sizing of matrices in Kalman Filter intialisation to fix resizing error/crash

nusight2/src/client/components/localisation/robot_model.ts, nusight2/src/shared/math/matrix3.ts, nusight2/src/shared/math/matrix4.ts
This PR adds multiply and invert methods to `Matrix4` and `Matrix3`.
No need to complicate consumers when we can hide the THREE conversions internally.
If performance was ever an issue we could also easily inline the math operations.
=> NUsight: Add matrix methods

shared/tests/utility/math/filter/TestFilters.cpp
I don't know why CI isn't picking up on this, but for me locally the Kalman Filter test fails.
It doesn't like that the B matrix is not being set a size and is then being passed into the constructor which expects a specific size.
=> Fix Kalman Filter test

module/platform/Webots/data/config/Webots.yaml
Goes with NUbots/NUWebots#102.
Standardising all comms to use port 10001. So we don't need to keep switching.
=> Use port 10001 by default in Webots, to standardise

module/extension/Director/src/director/reevaluate_group.cpp, module/extension/Director/tests/missing_provider.cpp, module/extension/Director/tests/watcher_removal_double_priority.cpp
We had some bug/s associated with these tests (mentioned in #975) that appear to have been fixed since I wrote down that they were an issue. In the spirit of having as many tests as possible so we don't reintroduce any bugs, I've created tests for these.
One test involves emitting a Task for which no Providers exist. 
The other test involves an existing test but without setting priority. It involves having two watchers. I have also changed the logic so that the order of equal watchers isn't changed, so that we can enforce that the first watcher will run over the second in the test. Otherwise the test is ambiguous as either watcher could run first.
=> Add Director tests for no-priority watchers and missing providers

tools/install.py
This PR fixes an issue with the `./b install` script. 
- Adds `local` variable
- Adds back in the ability to use `./b install n{number}`
=> Restore installing by robot name in `./b install`

tools/utility/dockerise/run.py
This functionality disappeared in #1090. I've added it in similarly to how it was before. Alternative to fix #1104, which is a bit yikes. 
Would be better if we could use cmake and check for the Webots module per-binary but this is hard.
=> Set hostname to webots if binary name has 'webots' in it

tools/utility/dockerise/run.py
Currently when running `./b install n{num}` there is an error `KeyError: 'args'`. This PR fixes this error by using the get() method with a default value to access the 'args' key from the kwargs dictionary. By providing a default value of an empty list [], we can safely check its length without raising an error.
=> Fix issue with `./b install`

module/extension/Director/src/director/run_task_pack.cpp
We've had a problem in Director where in webots, if keyboardwalk is started with the robot fallen over there is a stack overflow.
This same problem appears on the real robot in both robocup and keyboardwalk pretty much all of the time.
The problem is to do with dying tasks. When the dying tasks are removed, the groups are reevaluated. The group with the dying task still has it as a subtask. This causes an infinite loop of trying to run the task pack with the dying task, only to do nothing except delete the dying task, running the reevaluate group again... running the task pack with a dying task again...
The fix I found was to make sure that our group's subtasks are updated, then we remove the dying tasks.
With this, all existing tests pass, webots keyboardwalk on ground works, and the …
=> Fix stack overflow in Director where StandStill runs task pack in infinite loop with its dying child

module/platform/Webots/src/Webots.cpp
Webots is creating NBS files with incorrect length due to using the simulation time for webots images.
This PR updates the webots image timestamps to use `NUClear::clock::now()` which fixes the problem and I don't believe this introduces any problems.
=> Fix webots image timestamps

nusight2/NUsight2/package.json, nusight2/package.json, nusight2/src/client/components/three/stories/three_fiber.stories.tsx, nusight2/src/client/components/three/three_fiber.tsx, nusight2/yarn.lock
This PR adds react three fiber as a nusight dependency, and demonstrates its utility in a storybook.
It takes advantage of React's JSX, providing us a declarative language to describe threejs scenes.
I'm pretty convinced its superior to our current implementation is nearly every way, but the real proof will come when we rewrite the various components that use threejs (e.g. vision and localisation). I'm pretty confident it will simplify a lot, and that we should be able to maintain similar performance. See #938 for a previous attempt at porting vision.
Electing to keep this PR as minimal as possible for now.
=> Add react three fiber

.github/workflows/nusight.yaml, nusight2/src/client/components/localisation/network.ts
With the swap over to vite build no longer performs a type check. This adds type-checking back into CI
=> Add type checking to nusight

module/input/Camera/data/config/nugus1/Cameras/Left.yaml, module/input/Camera/data/config/nugus1/Cameras/Right.yaml, module/input/Camera/data/config/nugus2/Cameras/Left.yaml, module/input/Camera/data/config/nugus3/Cameras/Left.yaml, module/input/Camera/data/config/nugus4/Cameras/Left.yaml, module/input/Camera/data/config/nugus4/Cameras/Right.yaml
We've got new nucs (new nucs! new nucs!) and the robots have got different numbers to what they had before. We also have a fourth robot now. This is mostly from the top of my head so someone might want to check on each of the robots, but this does work for the fourth robot (currently Sarah). Frankie doesn't have a nuc yet but if all the others are right, then that one will be right too, since we haven't added any cameras, they've just moved about. 
- Sarah was number 1, is now number 4
- Kevin was number 3, is now number 2 (only has one camera)
- Sasha was number 2, now is Billie and is number 1
- Frankie will be number 3 and has one camera
=> Move cameras around with nucs 

roles/robocup.role
Some modules were missing from RoboCup and so things weren't working. Probs shows a problem with Director, it seems a high priority task that has no Provider will block all other tasks (has been added to the Director bugs issue).
=> Add missing modules to robocup

module/planning/PlanLook/src/PlanLook.cpp
We didn't have an idle in the look around Provider so there were no tasks between setting the look positions. This caused issues in other modules running when they shouldn't be.
=> Idle the look around when not choosing a new position

nusight2/src/client/components/vision/vision_camera/shaders/visual_mesh.vert, nusight2/src/client/components/vision/vision_camera/view_model.ts, nusight2/src/client/components/vision/vision_camera/visual_mesh.ts
Currently when the GL view's aspect ratio is wider than the image (usually the case when zoomed in), the mesh is rendered past the edges of the image. This PR fixes that by correcting the aspect ratio of the rendered mesh to match the image.
This is what it looked like before: 
And here's after:
=> Fix rendered visual mesh aspect ratio in NUsight

module/input/Camera/data/config/nugus2/Cameras/Right.yaml
Cameras on nugus2 and 3 were incorrectly assigned.
not 100% sure the serial number for nugus 3 is correct. The serial number in the yaml file on the robot right now should be correct if someone wants to check it.
=> rearranged some cameras

module/input/SensorFilter/src/SensorFilter.cpp, module/input/SensorFilter/src/SensorFilter.hpp, module/input/SensorFilter/src/sensorfilter/KalmanFilter.cpp, module/input/SensorFilter/src/sensorfilter/MahonyFilter.cpp
SensorFilter couldn't run without these messages before, making it hard to run smaller roles testing singular things eg the test/visualmesh role. This PR makes those optional in SensorFilter so it doesn't need them to run. The messages are only used to utilise the walk for positional odometry so if they don't exist it will skip that step. This works similar to how it skips it when the robot isn't walk/stable.
=> Make the WalkState and Stability messages optional in SensorFilter

module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp, module/platform/OpenCR/HardwareIO/src/HardwareIO.hpp, module/platform/OpenCR/HardwareIO/src/hardwareio/startup.cpp
This PR splits the watchdog into two so if we get dropped servo packets we recover quickly.
At the beginning, we get the OpenCR model. A model watchdog watches for this and times out after 300ms. This watchdog is disabled once the model is received.
When the model watchdog is disabled and the model is received, we enable the packet watchdog. This times out after 20ms of not getting a packet.
I've tested this under normal circumstances and it looks good. I've tested it under packet dropping circumstances and it also looks good, minimal impact on the walk. I did notice a slight impact on the walk but I'd say that is expected when all packets are dropping constantly.
There is an issue where the packet watchdog isn't disabling quickly enough at the beginning before the watchdog triggers …
=> Separate model and packet watchdogs to prevent dropped packets stopping the robot's motions

module/input/Camera/src/Camera.cpp
This PR fixes an issue with the latching method in `Camera.cpp` having incorrect logic for associating a sensors message to an image.
=> Fix images being out of sync with sensors

module/extension/Director/src/Director.hpp, module/extension/Director/src/director/find_ok_solution.cpp, module/extension/Director/src/director/run_task_pack.cpp, module/extension/Director/tests/self_intersection.cpp
Adds a unit test for Director self-intersection and provides a fix.
When a single Provider intersected with itself before with optional tasks, all of them would run even though they shouldn't.
E.g. if two optional tasks A and B were both emitted that needed C they would both run even though they intersected with each other.
This test was pulled out from #1108 as the way that test was written relies on this behaviour being correct
=> Add a unit test for Director self intersection and a fix

module/planning/PlanWalkPath/data/config/PlanWalkPath.yaml, module/skill/Walk/data/config/Walk.yaml, module/skill/Walk/data/config/nugus4/Walk.yaml, roles/test/behaviour.role, shared/utility/skill/WalkGenerator.hpp
This PR does the following:
- Fixes a bug with the `WalkGenerator` introduced when switching to the use of `Waypoint`. The z translational velocity of the swing foot and torso middle waypoint  was being set to `velocity_target.z()` when it is actually the angular yaw velocity.
- Simplifies generating trajectories slightly by merging three functions into a single one as they are only used once
- Slightly tunes billie walk params by adjusting pitch
- Tunes walk path planner (for walking to ball)
=> Walk bug fixes and tuning

module/input/Camera/data/config/nugus3/Cameras/Left.yaml, module/platform/OpenCR/HardwareIO/data/config/nugus3/HardwareIO.yaml
HardwareIO pitch offset was causing problems with the horizon, so it is gone
Moved around the camera since the nucs changed
horizon line looked okay and field lines looked alright.
=> Tune Sarah's camera horizon

module/vision/VisualMesh/data/config/nugus/VisualMesh.yaml
We are only running the left camera because the usbs are on the same bus, preventing us running two (lags too much). 
So this removes the right camera from the visual mesh config.
=> Remove Right camera in visualmesh config

module/vision/BallDetector/data/config/BallDetector.yaml
Tuning for ball detector for Robocup2023.
Slightly reduces confidence threshold and increases distance disagreement substantially.
=> Ball Detector Tuning Robocup2023

module/platform/OpenCR/HardwareIO/data/config/HardwareIO.yaml, module/platform/OpenCR/HardwareIO/data/config/nugus1/HardwareIO.yaml, module/platform/OpenCR/HardwareIO/data/config/nugus2/HardwareIO.yaml, module/platform/OpenCR/HardwareIO/data/config/nugus3/HardwareIO.yaml, module/platform/OpenCR/HardwareIO/data/config/nugus4/HardwareIO.yaml, module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp, module/platform/OpenCR/HardwareIO/src/HardwareIO.hpp, module/platform/OpenCR/HardwareIO/src/NUgus.hpp, module/platform/OpenCR/HardwareIO/src/hardwareio/process_data.cpp, module/platform/OpenCR/HardwareIO/src/hardwareio/send_request.cpp, shared/message/output/Buzzer.proto
This pull request aims to add a functionality for the OpenCR's buzzer. It cycles through all the servo motors and if it finds one servo that has a temperature that is above the configurable value, it writes the frequency value to the board and plays the sound of the buzzer.
Currently, a frequency of 0 is written to the board's buzzer but the functionality for the firmware  is already implemented in the firmware
=> Add buzzer functionality for the OpenCR board

docker/Dockerfile
Changes the ccache directory to the build directory so it persists between docker containers
=> Set ccache directory to the build directory so it is saved

nusight2/src/client/components/vision/vision_camera/shaders/visual_mesh.frag, nusight2/src/client/components/vision/vision_camera/shaders/visual_mesh.vert, nusight2/src/client/components/vision/vision_camera/visual_mesh.ts, nusight2/src/client/components/visual_mesh/camera/shaders/mesh.vert, nusight2/src/client/components/visual_mesh/camera/view_model.ts
The NUsight mesh colours are hardcoded with environment in the fourth position. Now that the network has an extra class, robots are the fourth index and environment is the fifth. This is consistent across the networks we have currently. 
NUsight has been displaying robots as black and ignoring environment (resulting in also black). 
This PR changes this so that robots appear in a different colour to the environment. 
Robots set to magenta.
=> Add robot mesh detections to NUsight visual mesh display

module/input/SensorFilter/data/config/SensorFilter.yaml, module/input/SensorFilter/data/config/webots/SensorFilter.yaml, module/input/SensorFilter/src/SensorFilter.cpp, module/input/SensorFilter/src/sensorfilter/KalmanFilter.cpp, module/input/SensorFilter/src/sensorfilter/MahonyFilter.cpp
This PR does the following:
- Adds ability to specifiy initial orientation for Mahony/Kalman filter
- Resets the dead-reckoned position of the robot on ResetFieldLocalisation
=> Add ability to specifiy initial orientation for Mahony/Kalman filter

module/planning/PlanLook/data/config/PlanLook.yaml, module/planning/PlanLook/data/config/webots/PlanLook.yaml
This PR adds the plan look search positions from competition which simply looks left and right due to larger FOV on real robot.
=> Update plan look search positions

module/input/SensorFilter/src/sensorfilter/RawSensors.cpp, module/platform/HardwareSimulator/src/HardwareSimulator.cpp, module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp, module/platform/OpenCR/HardwareIO/src/HardwareIO.hpp, module/platform/OpenCR/HardwareIO/src/hardwareio/construct_sensors.cpp, module/platform/OpenCR/HardwareIO/src/hardwareio/process_data.cpp, shared/message/input/Sensors.proto, shared/message/platform/RawSensors.proto, shared/utility/platform/RawSensors.hpp
Change RawSensors error handling to, broadly, stop odometry from exploding when we get any error. Now:
- Odometry will update regardless of *hardware* errors, and will only be conditional on subcontroller packet errors (which are the only ones relevant to the IMU)
- Other sensors message values will be conditional only to the specific errors which might be relevant, not just any error.
It also re-implements a check which disables the servo input voltage error as long as it's below the battery voltage. This was in the code previously but I removed it a while ago because I didn't know what it was for. Turns out it was important.
This also removes all references to Dynamixel protocol v1 errors which I'd left in pre-robocup for just-in-case compatibility, but are no longer needed. Hopefully …
=> Improve RawSensors error handling [HW-16]

module/actuation/Kinematics/data/config/webots/Kinematics.yaml, module/input/SensorFilter/data/config/webots/SensorFilter.yaml, module/platform/Webots/data/config/WebotsCameras/left_camera.yaml
Reason this wasn't working in Webots is because the folder isn't mounted in the webots docker container, so normally it would work but not if you're using the docker container for the purpose of virtual season or running multiple robots.
=> Fix urdf webots model path, specifically for webots docker

module/localisation/BallLocalisation/data/config/BallLocalisation.yaml
Currently the ball is initialized 0 meters away from the robot which sometimes causes the kick to be executed when the ball is first seen. This PR updates the initial x position of the ball to 5m.
=> Update initial x position in ball localisation

module/network/NetworkForwarder/src/NetworkForwarder.cpp, module/network/NetworkForwarder/src/NetworkForwarder.hpp
NetworkForwarder thought that if you set a field to "True" it meant limit to 1 FPS.
This fixes that
Have you
=> Fix NetworkForwarder to not think true means 1 FPS

.github/workflows/nusight.yaml
It seems like something in the Node 18 image we use in CI has changed such that [yarn can no longer find a globally installed node-gyp](https://github.com/NUbots/NUbots/actions/runs/6347202110/job/17241866951?pr=1245#step:6:19) to build native dependencies.
It [tries to install it on the fly but fails](https://github.com/NUbots/NUbots/actions/runs/6347202110/job/17241866951?pr=1245#step:6:21) since we have --prefer-offline (to use the cache) and it doesn't find node-gyp in the cache.
This PR adds the manual installation of `node-gyp` to the "Install dependencies" step to temporarily solve the issue. 
Thanks @JosephusPaye for fix.
=> Install node-gyp dependency manually

shared/tests/utility/math/angle.cpp, shared/utility/math/angle.hpp
Whenever you would use the acos of the dot product of two unit vectors (e.g.) `std::acos(uABb.dot(uCBb))` due to numerical instability it's possible for the dot product of (near) parallel or antiparalllel vectors to give values slightly above 1.0, when fed into `std::acos` this produces nan values which is bad.
The solution that is often done is to just clamp the output of the dot product between -1 and 1. However, this causes a loss of accuracy  (also you have to do clamping all the time).
A better way is described in https://www.plunk.org/~hatch/rightway.html
This PR adds a function to utility/angle and unit tests to ensure it works properly
Have you
You should go replace every place you `acos` the dot product of two unit vectors with this function!
=> Add function for finding `angle_between` two unit vectors in a numerically stable manner

module/input/SensorFilter/data/config/SensorFilter.yaml, module/input/SensorFilter/data/config/webots/SensorFilter.yaml, module/input/SensorFilter/src/SensorFilter.cpp, module/input/SensorFilter/src/SensorFilter.hpp, module/input/SensorFilter/src/sensorfilter/MahonyFilter.cpp, module/network/NetworkForwarder/data/config/NetworkForwarder.yaml, module/skill/Walk/src/Walk.cpp, shared/message/behaviour/state/WalkState.proto
The current method for estimating the x-y translation and yaw of odometry involves integrating the walk command. This PR replaces this with an "anchor point" method. We select an anchor point A which is a left/right foot base frame and assume that this point is in contact, fixed to the ground in world space, giving us Hwa. We then simply compute the pose of the torso from this frame (Hat) using kinematics. This allows us to compute Hwt = Hwa * Hat. Finally, we replace the roll and pitch components of the rotation using the Mahony filter estimation. After a step has been taken the anchor point is switched to the next planted foot, illustrated below.
A nice blog post can be found here discussing the idea: https://scaron.info/robotics/floating-base-estimation.html
This method can be improved …
=> Improve odometry with anchor point method

module/vision/VisualMesh/src/VisualMesh.cpp
Every time the robot falls over and can't see the ground, we get a log from the Visual Mesh module spamming to the terminal. This PR lowers the log level to `TRACE` so that it won't spam normally with the current `INFO` log level on the config file.
=> Stop Hcw log spam from Visual Mesh when robot falls over

module/extension/Director/src/director/run_task_pack.cpp
Previously if a subtask was Done, the parent could keep getting Done emits from the child which runs the parent Provider. We don't want to spam the parent. This was particularly a problem for the Servo Providers and caused issues with Sequences (and hence Scripts).
=> Stops subtasks spamming Done to their parent (fix issue with scripts not running properly)

module/localisation/FieldLocalisation/data/config/FieldLocalisation.yaml, module/localisation/FieldLocalisation/data/config/webots/FieldLocalisation.yaml, module/localisation/FieldLocalisation/src/FieldLocalisation.cpp, module/localisation/FieldLocalisation/src/FieldLocalisation.hpp, module/vision/FieldLineDetector/data/config/FieldLineDetector.yaml
This PR adds a config value for the following:
- Delaying the start of the filter (useful for letting odometry converge before beginning)
- Selecting a starting side (left, right or either)
=> Add delay and starting side options for field localisation

shared/utility/skill/scripts/nugus/Parkour.yaml
- Took it from the other PR of a similar name as the other branch was created off the robocup branch which had a bunch of other garbage. 
- The script should make the robot crawl up onto a platform of roughly knee height to the robot, on it's hands and knees  then crawl back down, ending up standing.
- This was made by just recording the robot getting onto the platform, then copying and reversing the yaml file.
=> Added Parkour script from robocup 2023

module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp, shared/utility/io/uart.cpp, shared/utility/io/uart.hpp
The UART utility had a few problems that needed fixing. This combines them all into one PR
Fixes include:
- Making the code clang-tidy conformant
- The extra static baud rate flags actually work since they don't have `elif`
- the low latency flag is always applied regardless of if it's using a custom baud or not
- make uart classes movable
=> Fix some issues in the uart utility

module/support/logging/DataLogging/data/config/DataLogging.yaml
This PR updates the default output directory for DataLogging from `logs` to `recordings`. This makes it easier to access the recorded  files since `recordings` in the container is symlinked to the local `recordings` folder.
Let me know if there's something special about the `log` directory that I'm missing. I know that on the robots we currently log to `log`, but changing that to recordings should be fine right? As long as we update docs.
NUbook PR: https://github.com/NUbots/NUbook/pull/301
=> Change DataLogging default directory to `recordings`

module/support/logging/DataLogging/data/config/DataLogging.yaml, module/support/logging/MessageLogHandler/CMakeLists.txt, module/support/logging/MessageLogHandler/README.md, module/support/logging/MessageLogHandler/data/config/MessageLogHandler.yaml, module/support/logging/MessageLogHandler/src/MessageLogHandler.cpp, module/support/logging/MessageLogHandler/src/MessageLogHandler.hpp, roles/test/messageloghandler.role, shared/message/nuclear/LogMessage.proto, shared/message/nuclear/ReactionStatistics.proto
This PR adds a new module `support::logging::MessageLogHandler`  that listens for `LogMessage` and `ReactionStatistics` messages from NUClear and recodes them into protobuf messages. This make it possible to record those messages to NBS files for later playback and analysis.
I'm hoping to get this in to use it for my NUsight workshop on Friday.
=> Add a module to convert NUClear Logs and ReactionStatistics to messages for recording

module/vision/BallDetector/src/BallDetector.cpp, module/vision/FieldLineDetector/src/FieldLineDetector.cpp, module/vision/GoalDetector/src/GoalDetector.cpp, shared/tests/data/TestConvexHull.yaml, shared/tests/utility/math/geometry/TestConvexHull.cpp, shared/utility/math/geometry/ConvexHull.hpp, shared/utility/vision/visualmesh/VisualMesh.hpp
Check was broken since it assumed above/below but we don't have above/below we have in/out. 
Added in tests for hull side check.
=> Fix check for in/out of convex hull

module/purpose/ScriptTuner/src/ScriptTuner.hpp, module/skill/Walk/data/config/Walk.yaml, module/skill/Walk/data/config/nugus1/Walk.yaml, module/skill/Walk/data/config/nugus3/Walk.yaml, module/skill/Walk/data/config/nugus4/Walk.yaml, shared/utility/skill/scripts/nugus/Stand.yaml, shared/utility/skill/scripts/nugus/Zombie.yaml
This PR reduces arm gains in walk engine as intermediate step to reduce the erratic movement when starting walk engine, however, we should figure out a better solution for this going forward.
Also reduces default gains in script tuner and various other scripts to prevent oscillations from overshoot.
=> Reduce default gains in various scripts and ScriptTuner

module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp
I'm not really sure why this works, maybe unbind doesn't actually disable it? But the problem with running scripts was that the model watchdog was enabled, and at some point in the script the packet watchdog ran and brought up that 'cannot run packet watchdog when model watchdog is enabled' log. At that point the hardware io loop is broken and the robot won't move again.
Adding the disable stops this from happening and the scripts all run fine (ran many times on two different robots).
=> Fix scripts cutting out when running / explicitly disable the model watchdog

nusight2/src/client/components/localisation/controller.ts, nusight2/src/client/components/localisation/grid/view.tsx, nusight2/src/client/components/localisation/model.ts, nusight2/src/client/components/localisation/skybox/view.tsx, nusight2/src/client/components/localisation/view.tsx
This PR does the following:
- Adds a grid floor plane to localisation view
- Adds toggle buttons in the menu to toggle visibility of individual components
=> Add grid floor plane and toggle menu to localisation view in NUsight

tools/format.py
The formatting of license headers is causing too many issues with CI. This PR temporarily comments out the formatting of license header files so that other PR's can be merged while it is fixed.
=> Temporarily remove formatting license headers

module/strategy/WalkToFieldPosition/src/WalkToFieldPosition.cpp, module/vision/VisualMesh/src/VisualMesh.cpp, shared/utility/localisation/OccupancyMap.hpp
Main currently has three asan errors that occur during normal `robocup` play. 
- FieldLocalisation: the occupany map rectangles were sometimes being created with negative length/width
- Vision: size of the matrices in the one-liner for rPWw were wrong
- WalkToFieldPosition: a 3d vector was initialised with only two values, leaving the last value uninitialised
=> Fix asan errors on main

module/input/SensorFilter/data/config/SensorFilter.yaml, module/input/SensorFilter/data/config/nugus/SensorFilter.yaml, module/input/SensorFilter/src/SensorFilter.cpp, module/input/SensorFilter/src/SensorFilter.hpp, module/input/SensorFilter/src/sensorfilter/KalmanFilter.cpp, module/input/SensorFilter/src/sensorfilter/MahonyFilter.cpp, module/input/SensorFilter/src/sensorfilter/UKF.cpp, roles/webots/localisation.role, roles/webots/robocup.role, shared/message/vision/Robot.proto
When the robot gets penalised, it's localisation becomes very off because it is moved in simulation or physically moved to a new position. We have a localisation reset to fix this, but it doesn't fully reset odometry when it resets localisation.
This PR resets the fiilters and odometry to the initial values from config.
=> More thoroughly reset odometry when resetting localisation 

module/input/Camera/data/config/Cameras/Left.yaml, module/input/Camera/data/config/nugus4/Cameras/Left.yaml, module/localisation/FieldLocalisation/src/FieldLineOccupanyMap.cpp, module/network/NetworkForwarder/src/NetworkForwarder.hpp, module/planning/PlanKick/data/config/PlanKick.yaml, module/planning/PlanKick/src/PlanKick.cpp, module/platform/OpenCR/HardwareIO/data/config/nugus4/HardwareIO.yaml, module/skill/Walk/data/config/nugus4/Walk.yaml, module/vision/BallDetector/data/config/BallDetector.yaml, module/vision/GreenHorizonDetector/data/config/GreenHorizonDetector.yaml, roles/scripttuner.role, shared/utility/skill/scripts/nugus4/StandUpFront.yaml
- Frankie's nuc was swapped for Kevin's, so now Frankie is `nugus4`. As such, Frankie's HardwareIO, Walk and Camera tunes have been moved to `nugus4`. The `nugus1` nuc isn't in a robot so nothing to change it to. 
- Adjusted the camera to make it brighter
- Tuned the `nugus4` Left.yaml pitch and yaw so field lines in localisation look correct
- Added back in the logic to field occupancy map to not draw the penalty box and crosses for the lab field
- Changed NetworkForwarder from `Buffer<10>` to `Single`. The reaction will only run one at a time and therefore should only be using one thread. This appears to fix our issues with the robot not walking if NetworkForwarder is in the role, and allows us to use nusight with the real robot while its moving.
-  Tuned kick planner a little bit to …
=> Tunes Frankie (nugus4) and small code changes for quality of life and fixes for the real robot and lab

roles/fake/keyboardwalk.role, roles/fake/visualmesh.role, roles/firmwareinstaller.role, roles/keyboardwalk.role, roles/natnet.role, roles/onboardwalkoptimisation.role, roles/playback.role, roles/ps3walk.role, roles/robocup.role, roles/scriptrunner.role, roles/scripttuner.role, roles/systemconfiguration.role, roles/test/behaviour.role, roles/test/camera.role, roles/test/director.role, roles/test/gamecontroller.role, roles/test/localisation.role, roles/test/messageloghandler.role, roles/test/nusight.role, roles/test/plotjuggler.role, roles/test/sensor.role, roles/test/speak.role, roles/test/visualmesh.role, roles/webots/behaviour.role, roles/webots/keyboardwalk.role, roles/webots/localisation.role, roles/webots/robocup.role, roles/webots/scripttuner.role, roles/webots/walkoptimisation.role, roles/webots/webots.role
- Remove unnecessary modules in some roles
- Clean up the grouping of modules
- Added/cleaned up comments for modules that might not be self explanatory
-  Added in a header for every role file explaining it's purpose
- Removed some roles. These were mostly ones made when testing during development of certain modules and for running CI, but other roles cover this testing now. 
For Jira DQA-4.
=> Clean up modules and comments in roles

doc/ArchInstall/arch-chroot_install.sh, module/tools/SystemConfiguration/data/system/default/etc/wpa_supplicant/wpa_supplicant-wlp0s20f3.conf
Epsilon-x was using the `wpa_passphrase` result for epsilon-z, but this is incorrect.
=> Fix wpa_supplicant config for epsilon-x

docker/nugus_sim/run.py
- corrects the path for webots so that multiple robots can be run. The run.py script was updating the wrong yaml file, so when running multiple robots in webots, they were all using the default settings. 
To test this, if you want: 
- make sure the GameController.yaml log level is set to "DEBUG"
- Print out the value of player_id in GameController::sendReplyMessage
log<NUClear::DEBUG>("packet->player", int(packet->player));
- run multiple robots (in the guides webots/running multiple robots) 
- check that each robot has a different player id
=> Fix Webots for Multiple Robots

module/localisation/RobotLocalisation/data/config/RobotLocalisation.yaml, module/localisation/RobotLocalisation/src/RobotLocalisation.cpp, module/localisation/RobotLocalisation/src/RobotLocalisation.hpp, shared/message/vision/Robot.proto
- data association function: removed tracked robots as it's a class variable, updated docs
- Changed the part where the current tracked robots are checked over to make it a bit less indented/possibly easier to read, merged the two steps as well, and also stopped using the remove_if as it `move`s the tracked robots, which is why the `id` being `const` was a problem as it basically makes new tracked robot and copies the original contents
- Made the `id` in tracked robot `const`, also made the `next_id` an unsigned long cause I'm lowkey worried about overflow
- Got rid of the make new robot function, moved most of the stuff for setting up the ukf into the constructor, and did an `emplace_back` so we can add to the vector and make a robot at the same time
- Added a `get_rRWw` function because …
=> Some changes to the robot localisation code [base is not main!]

module/localisation/FieldLocalisation/data/config/FieldLocalisation.yaml, module/localisation/FieldLocalisation/data/config/webots/FieldLocalisation.yaml, module/localisation/FieldLocalisation/src/FieldLocalisation.cpp, module/localisation/FieldLocalisation/src/FieldLocalisation.hpp, module/platform/Webots/src/Webots.cpp, shared/message/platform/RawSensors.proto, shared/message/platform/webots/messages.proto
Adds graphs for debugging localisation error using Webots ground truth data, like #1132 does for odometry.
Relevant changes to NUWebots:
https://github.com/NUbots/NUWebots/pull/111
=> Add localisation ground truth method

nusight2/src/server/dev.ts, nusight2/src/server/prod.ts
This PR solves unreliable connection between NUbots binary and NUsight. Works for both docker and real robot in lab.
=> Change default nuclearnetAddress address to use multicast

tools/run.py
ngl kinda confused as to when this broke and why this wasn't a problem before (did we rename the user?)
In the docker container, the user is `nubots`, not `NUbots`, so the log_path to save ASan logs to was wrong.
=> Fix running with ASan by fixing the directory name

module/purpose/Soccer/src/Soccer.cpp
When we have force-playing on, we want to keep in the play state regardless of what GameController does. This PR ignores penalisation state changes when force playing.
=> Stop penalisation when force playing

docker/Dockerfile
OpenVino and OpenCV take quite a while to build from source so tthis PR moves them to earlier in the Dockerfile to help with caching and build times.
Additionally, the library `lame` is built from source now so installing to the robot correctly moves across the required libraries.
=> Shuffle around docker file

shared/extension/Configuration.hpp
Wrong variable used in empty check. If no robot config, don't bind.
Also fixes multiple binding when the platform and hostname are equal, eg 'webots'
=> Fix multiple default config running on install

module/skill/SplineKick/src/SplineKick.cpp, shared/utility/skill/KickGenerator.hpp
This PR updates spline kick configuration to clear waypoints on configuration. This fixes the bug where if configuration ever runs multiple times timing between waypoints in broken. 
Improvement: We should also look at sorting waypoints in the trajectory class by time to allow waypoints to be added out of order.
=> Clear spline kick waypoints on configuration

module/skill/Walk/data/config/kevin/Walk.yaml, module/skill/Walk/data/config/webots/Walk.yaml, module/skill/Walk/src/Walk.cpp, shared/message/behaviour/state/WalkState.proto, shared/utility/skill/WalkGenerator.hpp
This PR adds a STARTING state to the walk generator. The state is entered when first starting to try walk and shifts the torso above the planted foot before taking a step. This improves the reliability of starting a walking motion.
Also, tunes kevins walk.
=> Add STARTING state to walk generator

module/platform/NUSense/HardwareIO/src/HardwareIO.cpp, shared/message/platform/NUSenseData.proto
Adds some more tailored handling and raising of errors for NUSense.
- Logs the count of packet-errors, CRC-errors, and timeouts.
- Logs a dispatch as a message from NUSense for fleeting errors; this is a generic error-field.
Have you
Work in progress.
=> Add error and fault handling for NUSense.

roles/webots/robocup.role
Field localisation needs field intersection points, which comes from yolo. Without yolo localisation won't run and some behaviour modules wont run either.
=> Add Yolo module into the Webots RoboCup role

module/localisation/FieldLocalisationNLopt/data/config/FieldLocalisationNLopt.yaml
When I was running in the lab,it wasn't localising until I set this to either. It worked with either and makes sense to have it as either.
=> Set default NLopt field localisation config to start on EITHER side of the field

module/planning/PlanLook/src/PlanLook.cpp, module/purpose/Soccer/src/Soccer.cpp, module/purpose/Soccer/src/Soccer.hpp, module/purpose/Tester/src/Tester.cpp, module/purpose/Tester/src/Tester.hpp, module/strategy/AlignBallToGoal/src/AlignBallToGoal.cpp, module/strategy/KickToGoal/src/KickToGoal.cpp, module/strategy/Ready/src/Ready.cpp, module/strategy/StrategiseLook/src/StrategiseLook.cpp, module/strategy/WalkToBall/src/WalkToBall.cpp, module/strategy/WalkToFieldPosition/src/WalkToFieldPosition.cpp
Our behaviour providers need to run at some frequency to check if things change, often time based things. Currently we've been doing this per-Provider but then if a parent and child are both running eg 10 times a second, this will compound for the child if the parent is triggering the child each time. The PR just makes the root update 10 times/second. 
Things wouldn't run if idle'd, but thats only really used lower down. Main motivation is for walk path planner to have reasonable dt for new method.
Tested in webots.
=> Have root set the frequency update for behaviour providers

module/localisation/RobotLocalisation/src/RobotLocalisation.cpp, module/vision/BallDetector/data/config/BallDetector.yaml, module/vision/GreenHorizonDetector/data/config/GreenHorizonDetector.yaml, module/vision/GreenHorizonDetector/src/GreenHorizonDetector.cpp, module/vision/GreenHorizonDetector/src/GreenHorizonDetector.hpp, module/vision/Yolo/README.md, module/vision/Yolo/data/config/Yolo.yaml, module/vision/Yolo/src/Yolo.cpp
- Tune the VMesh Ball Detector to focus more on seeing balls further away. Upped the min distance so it ignores balls close by. Upped the cluster size so small 'balls' don't get through, as small balls are thought to be far away.
- Tune the YOLO detector to allow through balls at a much lower confidence (this helped with balls on field lines and paler balls)
- Added in heuristic to YOLO detector to not allow balls, robots and field intersections if they are outside of the green horizon. 
- Tuned the green horizon to allow lower confidence field points, as it was not covering the whole field sometimes. Helped a lot.
- Removed the check for if the robot is in the green horizon in the RobotLocalisation module as this is already done in the Yolo module. Had to keep in one check and the …
=> Vision heuristics with YOLO + VMesh (mostly balls)

shared/utility/skill/WalkGenerator.hpp
The walk engine will get stuck in the STOPPING state if the robot switches between stopping and then getting a new non-zero command. This happens when switching quickly between the WalkTo Task and the TurnOnSpot Task. 
This PR adds to the condition that STOPPED can be achieved if the step is over and the robot is STOPPING. This allows the walk engine to continue to walking again after stopped.
=> Fix Walk Engine States - Stuck in STOPPING when non-zero command requested before STOPPED

module/strategy/FindObject/data/config/FindObject.yaml, module/strategy/FindObject/src/FindObject.cpp, module/strategy/FindObject/src/FindObject.hpp
It was originally made without this check because the idea was it was running at the lowest priority and would take over if the walk to ball/look at ball couldn't run. But this makes it unnecessarily request Tasks and it is a problem if we want to stand still sometimes when we can see the ball (ie goalie and defender).
=> Make FindBall only look if it can't see the ball

module/purpose/KeyboardWalk/src/KeyboardWalk.cpp, module/purpose/ScriptTuner/src/ScriptTuner.cpp, module/tools/RoboCupConfiguration/src/RoboCupConfiguration.cpp
This PR fixes a bug where ncurses menu freezes. The issue is something related to using `getch()` in combination with `on<IO>`. Setting up `STDIN` to non-blocking and not requiring an EOF  fixes the issue.
=> Fix bug where ncurses menu can freeze

module/purpose/KeyboardWalk/src/KeyboardWalk.cpp
Emitting stand still on startup can cause seg fault which leads to robot falling over. Temporarily fix is provided by commenting this out
=> Temporary fix for robot crashing on startup

module/strategy/WalkToBall/data/config/WalkToBall.yaml, module/strategy/WalkToBall/data/config/webots/WalkToBall.yaml, module/strategy/WalkToBall/src/WalkToBall.cpp, module/strategy/WalkToBall/src/WalkToBall.hpp
This PR adds some additional path planning to `WalkToKickBall` to avoid colliding with ball when approaching from "in front"
=> Add unwanted ball collision avoidance

module/purpose/ScriptTuner/src/ScriptTuner.cpp
Adds an additional space after `Left` so that left and right servos have their names aligned :)
=> Align servo names in scripttuner for readability

module/purpose/KeyboardWalk/src/KeyboardWalk.cpp, module/purpose/ScriptTuner/src/ScriptTuner.cpp, module/tools/RoboCupConfiguration/src/RoboCupConfiguration.cpp
Recent PR which fixed ncurses freezing has introduced bugs. This PR reverts changes made and just uses ` on<Always>` for scripttuner main thread which fixes the freezing issue.
=> Revert scripttuner bug fix and use on<Always> instead

module/platform/OpenCR/HardwareIO/data/config/HardwareIO.yaml, module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp, module/platform/OpenCR/HardwareIO/src/hardwareio/process_data.cpp, module/purpose/KeyboardWalk/src/KeyboardWalk.cpp
This PR:
- Fixes issues which were breaking buzzer functionality
- Not setting the dirty flag on `opencr_state`
- Emitting `Buzzer` 0's when servos are not hot (which cancelled out with other buzzer emits).
- Makes the temperature alarm frequency more annoying.
- Adds `WARN` logging when temperature alarm is enabled, and `DEBUG` logging for any buzzer message.
These fixes implement the buzzer functionality for #1393
=> OpenCR buzzer fixes

module/purpose/Striker/data/config/Striker.yaml, module/purpose/Striker/src/Striker.cpp, module/purpose/Striker/src/Striker.hpp
In kickoff, we now keep walking to the ready position if it's the opponent's kickoff. If the ball moves enough away from the center of the field, we assume they have touched the ball and we can play.
Secondary time is used to determine if kickoff time is finished as this time shouldn't be used for anything else unless it's in a mode like direct free kick etc, but in that case we'd be in a different Provider and it wouldn't matter. 
Kickoff applies not just to the start of a half, but also whenever a robot scores a goal. These cases were all tested in Webots. 
The distance for the ball to move to assume kickoff is over seems to be large in webots so hopefully is okay even if localisation has a bit of error.
Only applies to Striker as the others wouldn't attempt to touch the ball in this …
=> Add logic for whether to approach ball in kickoff 

module/input/SensorFilter/src/SensorFilter.cpp
This PR removes resetting the mahony filter when resetting localisation so roll and pitch are still accurate.
=> Remove reseting mahony filter when resetting localisation

module/input/SensorFilter/src/SensorFilter.cpp, module/purpose/Soccer/src/Soccer.cpp
Button presses were getting skipped due to Single in each button trigger. Removing single seems to have fixed the issue.
=> Remove Single to fix buttons when running robocup

module/network/RobotCommunication/data/config/RobotCommunication.yaml, module/network/RobotCommunication/src/RobotCommunication.cpp, module/network/RobotCommunication/src/RobotCommunication.hpp
This PR adds a UDP filter similar to GameController so that we ignore robots that don't match our filter address.
=> Add UDP filter to robot communication

module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp, module/platform/OpenCR/HardwareIO/src/HardwareIO.hpp, module/platform/OpenCR/HardwareIO/src/hardwareio/create_watchdogs.cpp, module/platform/OpenCR/HardwareIO/src/hardwareio/startup.cpp
Splits out watchdog refactors (not incl uart flush) from #1441
=> Cleanup watchdog creation into functions

shared/utility/skill/WalkGenerator.hpp
When entering the `STOPPED` state the `Hps` transform is not updated. This breaks the first trajectory generated after leaving the stopped state. This PR fixes this bug by resetting the walk engine when in the stopped state, essentially, setting everything to their default initial state.
=> Fix bug in walk engine

module/platform/OpenCR/HardwareIO/src/hardwareio/construct_sensors.cpp
Duplicate of #1458 but for `main` instead of `robocup`.
subcontroller_error masked in all dynamixel packet errors from all devices. this was done before masking out the alert bit for battery voltage errors, which meant that we had a nonzero subcontroller_error if the battery was fresh (because servos would report a voltage error).
then button debouncing ignored buttons when we had a subcontroller error, causing the problem.
we now keep the subcontroller error check, but don't consider servo errors as subcontroller errors anymore. which is better.
=> fix buttons not working when battery voltage is low

module/tools/RoboCupConfiguration/data/config/RoboCupConfiguration.yaml
They ended up using a different one to the one we were told. This fixes the config so it has the right SSIDs for the RroboCup fields.
=> Update RoboCup Field SSIDs

module/actuation/FootController/src/FootController.cpp, module/actuation/Kinematics/src/Kinematics.cpp, module/actuation/Servos/src/Servos.hpp, module/skill/Walk/src/Walk.cpp
This PR updates all providers which are related to the walk engine to be high priority. The aim of this is to ensure that the walk engine always runs despite any computational conflict.
=> Make walk related modules high priority

module/tools/RoboCupConfiguration/README.md, module/tools/RoboCupConfiguration/data/config/RoboCupConfiguration.yaml, module/tools/RoboCupConfiguration/src/RoboCupConfiguration.cpp, module/tools/RoboCupConfiguration/src/RoboCupConfiguration.hpp
This PR aims to make it simpler to change IPs and networks by toggling in the robocup configuration tool. This is mostly useful at RoboCup. The IPs in the config shouldn't need changing, but the SSID and passwords of the fields may change next year. I'll keep the ones from this year in as placeholders.
The toggle for IP will look for any X placeholder and replace it with the current player ID for ease.
=> Add IP, SSID and password toggles to the RoboCup configuration tool

module/purpose/AllRounder/src/AllRounder.cpp, module/purpose/AllRounder/src/AllRounder.hpp, module/purpose/Defender/src/Defender.cpp, module/purpose/Defender/src/Defender.hpp, module/purpose/Goalie/src/Goalie.cpp, module/purpose/Goalie/src/Goalie.hpp, module/purpose/Striker/src/Striker.cpp, module/purpose/Striker/src/Striker.hpp, module/purpose/Tester/src/Tester.cpp, module/strategy/WalkInsideBoundedBox/src/WalkInsideBoundedBox.cpp, module/strategy/WalkToBall/src/WalkToBall.cpp, module/strategy/WalkToFieldPosition/data/config/WalkToFieldPosition.yaml, module/strategy/WalkToFieldPosition/data/config/webots/WalkToFieldPosition.yaml, module/strategy/WalkToFieldPosition/src/WalkToFieldPosition.cpp, module/strategy/WalkToFieldPosition/src/WalkToFieldPosition.hpp, shared/message/strategy/WalkToFieldPosition.proto
This PR adds functionality to `WalkToFieldPosition` where robot will stop once reaching the target position on the field. Additionally, a flag is added to the `WalkToFieldPosition` message to toggle this feature off, which is useful when walking to ball for dribbling.
=> Add stop at target functionality to WalkToFieldPosition

module/network/RobotCommunication/src/RobotCommunication.cpp
Noticed when GameController didn't exist but RobotComms did, it seg faults. Optional GameState is used without checking for nullptr first. Fixed up so there's a check.
=> Fix R2R seg fault by checking if GameState is null first

docker/etc/pacman.d/mirrorlist
Arch mirrors were failing, this adds a few more to the mirrorlist.
I'll also manually build the image and push it to DockerHub to make sure it works.
=> Add more date locked arch mirrors to try and improve reliability

module/platform/NUSense/HardwareIO/src/HardwareIO.cpp
Fixes a small bug where we forgot to add the offsets and switch the directions on the goal-positions received from NUSense. I am not sure whether this bug had a big effect on walking, etc., but it did affect the goal positions plotted on PlotJuggler.
Have you
=> Correct the goal-positions read from the NUSense state with the offsets and the directions.

nusight2/src/client/components/localisation/view.tsx, nusight2/src/client/components/odometry/odometry_visualizer/stories/robot_odometry.stories.tsx, nusight2/src/client/components/robot_selector/stories/robot_selector.stories.tsx, nusight2/src/client/components/three/stories/render_targets.stories.tsx, nusight2/src/client/components/three/stories/three.stories.tsx, nusight2/src/client/components/three/three.tsx
The `disposeOnUnmount` function is deprecated in MobX 6 and its invocation will throw an error. This PR replaces all usages with a manual dispose method to prepare for such a day (#1503).
Converting classes to functional components would likely be a cleaner solution, but would come with a much greater scope of work.
=> [NUsight] Remove disposeOnUnmount usages

module/platform/NUSense/HardwareIO/data/config/billie/HardwareIO.yaml, module/platform/NUSense/HardwareIO/data/config/frankie/HardwareIO.yaml, module/platform/NUSense/HardwareIO/data/config/kevin/HardwareIO.yaml
Noticed when using Billie yesterday that the offsets in the NUSense HardwareIO were wrong (I assume old) and copying over the OpenCR config fixed it. Did the same for the others too.
=> Update NUSense offsets to current OpenCR offsets

module/support/configuration/GlobalConfig/data/config/nugus2/GlobalConfig.yaml, module/support/configuration/GlobalConfig/data/config/nugus3/GlobalConfig.yaml, module/support/configuration/GlobalConfig/data/config/nugus4/GlobalConfig.yaml
This means that the robots will have the player ID corresponding to their nuc number automatically.
=> Add robot-specific player ID config

module/extension/Director/src/director/run_task_pack.cpp, shared/extension/Behaviour.hpp, shared/extension/behaviour/ProviderScope.hpp, shared/extension/behaviour/task_types.hpp, shared/extension/behaviour/unique_tasks.hpp
Instead of emitting the task pack to Director and getting `run_task_pack` to check for `Continue`s, just do the check in the Behaviour extension before it reaches the Director. 
The purpose of this is to reduce the number of things the Director thread needs to do, as it is running on one thread with a lot to do.
=> Skip Continues in the Behaviour extension rather than the Director

docker/Dockerfile, module/platform/Webots/src/Webots.cpp, module/vision/VisualMesh/data/config/webots/VisualMesh.yaml, module/vision/Yolo/data/config/webots/Yolo.yaml, module/vision/Yolo/src/Yolo.cpp, tools/utility/dockerise/run.py
This PR make required changes to use opencl engine with the VisualMesh which increases runtime performance in webots a considerable amount. The user will need to have a gpu/igpu which supports opencl.
This requires the following PR on the webots side : https://github.com/NUbots/NUWebots/pull/103
=> Add ability to use VisualMesh with GPU in Docker + Change webots image format to RGBA

.github/workflows/nubots.yaml, .github/workflows/nusight.yaml
The purpose of this PR is to fix NUsight's CI as it's currently broken. 
The CI issue does not come up locally, as it works in the Docker environment. However, the CI workflow does not use Docker and instead installs node and runs NUsight from the `nusight2` folder. Since intended workflow is to run through Docker with the `b` script, rather than directly running NUsight, this PR updates the NUsight workflow to use Docker and the `b` script. 
CI passes and all looks good :shipit:
=> Update NUsight GitHub Actions workflow to use the Docker image

shared/utility/skill/Script.hpp
`play` not working was because we have a new enum for 'when should a servo be considered done?' in the `ServoCommand` message, and while it was set to `TIME`-based in the normal script function, there was another overloaded function missed here (which is used by script tuner) that hadn't got the field set. Since it wasn't set, it defaulted to `NONE`.
This PR sets the servo Done condition to `TIME` for the load_script function that was missed in the original PR and results in `play` working in script tuner.
=> Fix script tuner play by specifying TIME as the done condition for scripts

.github/workflows/images.yaml, .github/workflows/nubots.yaml, .github/workflows/nusight.yaml, docker/Dockerfile
A couple of PRs the last few days have encountered this issue where our Docker image is using too much disk space. We run CI on Ubuntu, and there are many packages that can be cut down to gain disk space. 
This tool https://github.com/marketplace/actions/free-disk-space-ubuntu seems to be a nice addition to do this, and cuts almost 30GB leaving us with room for growth.
Tested with adding libraries, observing it fail from disk space error, and applied the workflow update which resulted in the checks passing. Reverted the added libraries.
=> Fix GitHub actions runner out of memory during docker image build

nusight2/src/client/components/localisation/r3f_components/text_billboard.tsx, nusight2/src/client/components/localisation/r3f_components/text_geometry_helper.tsx
When running `./b yarn start`, I encountered the warning
```
Warning: Do not call Hooks inside useEffect(...), useMemo(...), or other built-in Hooks. You can only call Hooks at the top level of your React function. For more information, see https://reactjs.org/link/rules-of-hooks Error Component Stack
at TextBillboard (text_billboard.tsx:43:3)
at PurposeLabel (purpose_label.tsx:18:3)
at object3D (<anonymous>)
```
There was also another warning to do with height being deprecated for depth. 
This PR updates the billboard text code to no longer produce either of these warnings.
=> Fix warnings in NUsight coming from text component

module/localisation/RobotLocalisation/src/RobotLocalisation.cpp, module/localisation/RobotLocalisation/src/RobotLocalisation.hpp
I've made some refactoring changes while working on team association, and so to keep that PR focused and to reduce issues later (given there are a few people working in this file on different projects), I've moved those changes into this PR. It aims to keep steps of the localisation method discrete and contained in functions.
Tested in webots, looked good.
=> Refactor RobotLocalisation to make way for more functionality (eg team association)

module/purpose/Soccer/data/config/Soccer.yaml, module/purpose/Soccer/src/Soccer.cpp, module/purpose/Soccer/src/Soccer.hpp
Currently we set the gains of the servos to a low value when starting the robot up which is great to avoid having the robot aggressively move to its nominal standing pose, however, this causes problems when behaviour modules want to request the robot to walk immediately. This PR solves this problem for `robocup` by adding a short start up delay to the Soccer module. A better fix will be to revive and test `StartSafely`
=> Add a startup delay in Soccer

module/network/RobotCommunication/data/config/RobotCommunication.yaml, module/network/RobotCommunication/src/RobotCommunication.cpp, module/network/RobotCommunication/src/RobotCommunication.hpp
The robot sends a message to its team mates pretty much immediately, but the system isn't really in a good spot yet. Everything is essentially zero, and localisation needs a bit to settle anyway. This PR adds a delay before sending any messages, so that there is a higher chance their data is useful.
Practically, this prevents the team robot localisation from thinking there is a team mate in the center of the field.
=> Add a delay to RobotCommunication to prevent empty/incorrect messages

tools/build.py
Missed adding this arg in the `configure` step of `build.py` which runs if we don't have a ninja build file.
=> Add build_dir arg to build.py configure step

module/actuation/KinematicsConfiguration/data/config/KinematicsConfiguration.yaml, module/purpose/PS3Walk/data/config/PS3Walk.yaml, module/purpose/PS3Walk/src/PS3Walk.cpp, module/purpose/PS3Walk/src/PS3Walk.hpp, roles/keyboardwalk.role, roles/ps3walk.role
This PR does the following:
1. Adds acceleration limit to joystick commands to improve controlling robot with ps3 controller sticks
2. Adds scripts/button mapping to configuration file (disables scripts by default, toggled with R2)
3. Adds new limits to the head pitch/yaw to prevent head servos reaching limits
4. Lock head by default
5. Adds nusight stuff to both ps3walk and keyboardwalk
=> Improve ps3walk walk command output

module/extension/FileWatcher/data/config/FileWatcher.yaml
Noticed recently filewatcher was broken on the robot, this missing config is probably why
=> Add filewatcher config

module/localisation/RobotLocalisation/src/RobotLocalisation.cpp, module/localisation/RobotLocalisation/src/RobotLocalisation.hpp, shared/message/localisation/Robot.proto
- Added penalised information so we can track the info without any extra overhead - I did consider using the TeamMates message and tracking separately, but I'd rather replace all of that with just the `localisation::Robots` moving forward. No point in tracking robots twice. 
- Set defaults for teammate id and penalised so we don't need to explicitly set them in the VisionRobots loop
- Added a sort before the maintenance loop to put teammates first. This is because I noticed a bug where if a teammate and 'opponent' were too close, it would delete the teammate and just keep tracking it as an opponent. This should now add the teammate to the new vector and any opponents that are too close would be removed instead.
- Realised that if we see no robots and get no teammate messages, nothing runs …
=> Fixes to RobotLocalisation and add penalisation info for teammates

roles/fake/keyboardwalk.role, roles/keyboardwalk.role, roles/test/localisation.role, roles/webots/demo.role, roles/webots/keyboardwalk.role, roles/webots/localisation.role, roles/webots/logging.role
Keyboardwalk has it's own console log handler to work better with ncurses menu. This PR removes console log handler from modules with keyboard walk to prevent double up logs in console.
=> Remove console log handler from modules with keyboardwalk 

shared/utility/vision/visualmesh/VisualMesh.hpp
Tested in Webots. Biggest bottleneck from GreenHorizon is the clustering, everything else is less than a millisecond. Normally we cluster after extracting boundaries, so the computation isn't a big deal, but somehow this is unstable with the GreenHorizon so the algorithm first clusters, then extracts the boundary. 
Old method took about  >100ms, this takes about <2ms in webots. 
Now tiny in trace files rather than showing up as very long processes.
=> Decrease compute time of GreenHorizon by switching to a faster clustering algorithm

module/localisation/FieldLocalisationNLopt/src/FieldLocalisationNLopt.cpp
The data association function is run in the main loop for NUsight visualisation purposes without checking if its nullptr. The function itself doesn't check for nullptr, even though its a shared pointer. This PR fixes this by returning an empty vector if field intersections doesn't exist or is empty.
I encountered this while testing on the real robot - it's pretty uncommon for the robot to start without any field intersections seen at all though.
=> Prevent segmentation fault in field localisation when no field line intersections exist

module/skill/KickWalk/data/config/KickWalk.yaml, module/skill/KickWalk/src/KickWalk.cpp, module/skill/KickWalk/src/KickWalk.hpp, module/skill/Walk/data/config/webots/Walk.yaml, module/skill/Walk/src/Walk.cpp, module/skill/Walk/src/Walk.hpp, shared/message/skill/Walk.proto
- Moves logic for leg and phase into the Walk module
- Start kicking at the end of the previous step (could try out start of kick step instead) 
- End at the end of the step
- Adds a wait into the KickWalk so multiple kicks aren't trigged in succession
Looks pretty clean in Webots.
@Crafty15 hopefully this helps with the timing. Feel free to merge if you want to use it.
=> [Merge into a feature branch, not main] Use the walk generator's clock and step period to stop/start the kick

module/purpose/FieldPlayer/src/FieldPlayer.cpp
I think this got lost in some of the clean up. Seg fault if no ball is seen at all yet in the program.
=> Check ball for nullptr before proceeding in FieldPlayer

module/tools/RoboCupConfiguration/src/RoboCupConfiguration.cpp, module/tools/RoboCupConfiguration/src/RoboCupConfiguration.hpp
The old way of reading config files was just a simple solution and didn't take into account merging, it just opened only the deepest file. This doesn't work when the fields are split across files, eg the default and a `nugus3` file. This PR instead uses the Configuration struct in the extension file. Saving also now checks for platform config. Saving still just dumps to one file for ease. 
I've also switched from `Soccer` to `SoccerNew` for game-specific config fields. 
This should fix the issues we've seen during practice games.
=> Upgrade RoboCupConfiguration tool to use the Configuration extension and use SoccerNew

nuclear/README.md, nuclear/cmake/Scripts/generator/OneOfField.py, nuclear/cmake/Scripts/generator/OneOfType.py, pyproject.toml, uv.lock
Replace abandonware `stringcase` package, which was causing the following errors when building due to not using raw strings:
```
...
[47/1097] Building classes for /home/nubots/NUbots/shared/message/input/GameState.proto
/home/nubots/build/.venv/lib/python3.12/site-packages/stringcase.py:247: SyntaxWarning: invalid escape sequence '\W'
return re.sub("\W+", "", string)
...
```
Chose `casefy` ([github](https://github.com/dmlls/python-casefy), [PyPI](https://pypi.org/project/casefy/)) as it's a `stringcase` replacement created in response to `stringcase`'s abandonment, and has a compatible API. Also considered `stringcase-new` ([GitHub](https://github.com/zahlman/stringcase-new), [PyPI](https://pypi.org/project/stringcase-new/1.2.2/)) which is a complete drop-in replacement for `stringcase`, …
=> Replace `stringcase` with `casefy` to fix warnings.

module/localisation/BallLocalisation/data/config/BallLocalisation.yaml, module/localisation/BallLocalisation/src/BallLocalisation.cpp, module/network/RobotCommunication/data/config/RobotCommunication.yaml, module/network/RobotCommunication/src/RobotCommunication.cpp, module/network/RobotCommunication/src/RobotCommunication.hpp, shared/message/input/RoboCup.proto, shared/message/localisation/Ball.proto
Just some more things I noticed. If the ball is completely lost, the robots will keep echoing to each other. 
Added in a confidence on the ball, so that we can ignore balls that are not firsthand knowledge. 
Even then, there is an issue with old confident ball messages being sent to teammates, so I've added time filtering on the emission of balls.
This should be the last thing - works well in webots when I test it.
=> [Merging into feature branch] Consider case where ball is missing, prevent echoes

tools/nbs/video.py, tools/utility/dockerise/register.py, tools/utility/nbs/protobuf_types.py
#1556 removed some `try`/`except` blocks in `b.py` which were hiding errors. For the last two months, `b` would error if run without a tool (e.g. `./b --help`).
These errors have been fixed:
- Add system libraries to the protobuf include path in `tools/utility/nbs/protobuf_types.py` (whether this caused an error seems to be platform-specific)
- Add default arguments to the `image` kwarg of `tools/utility/dockerise/register`.
- Unclear if this was the best way of doing it, but it mirrors what's done in `tools/utility/dockerise/run_on_docker` and fixes the issue.
Some annoying logs when running `./b help` have been suppressed by setting the Tensorflow log level in `tools/nbs/video.py`, matching what is already done in `tools/nbs/calibrate_cameras.py`. 
Other annoying logs I haven't been …
=> Fix some `b.py` errors which stop `--help` from running.

module/localisation/RobotLocalisation/data/config/RobotLocalisation.yaml, module/localisation/RobotLocalisation/src/RobotLocalisation.cpp, module/localisation/RobotLocalisation/src/RobotLocalisation.hpp, module/network/RobotCommunication/src/RobotCommunication.cpp, module/purpose/FieldPlayer/data/config/FieldPlayer.yaml, module/purpose/FieldPlayer/src/FieldPlayer.cpp, module/purpose/FieldPlayer/src/FieldPlayer.hpp, module/purpose/Support/CMakeLists.txt, module/purpose/Support/README.md, module/purpose/Support/data/config/Support.yaml, module/purpose/Support/src/Support.cpp, module/purpose/Support/src/Support.hpp, module/strategy/FindObject/src/FindObject.cpp, roles/robocup.role, roles/webots/robocup.role, shared/message/input/RoboCup.proto, shared/message/strategy/FindBall.proto, shared/utility/strategy/soccer_strategy.hpp
A few bug fix and setup things in here too, to make things work nicely.
- RobotLocalisation: Added a check to ignore teammates who have a high localisation cost.
- RobotLocalisation: Fixes a bug where the purpose wasn't being overwritten when a new message is received from a tracked teammate.
- RobotCommunication: Made GlobalConfig required, because otherwise there is not team ID associated with the message, which isn't helpful.
- RobotCommunication: Added the cost of localisation, to support first point above.
- RobotCommunication: Purpose player ID is overwritten with the global config player ID. This is to enforce consistency, as the global config is the main truth of player ID, and for empty purpose messages to still contain the correct player ID.
- FieldPlayer: Search if localisation …
=> Add functionality for a support player

module/purpose/KeyboardWalk/src/KeyboardWalk.cpp
This PR provides a temporary fix for keyboard walk freezing when using the keyboard. The fix is sub-optimal as it locks up a thread purely for listening for keyboard events, but it's a fix... 
The real issue is something to do with using `getch()` and `on<IO>` together resulting in the module freezing, but I don't have a fix for it currently.
=> TEMP: Fix keyboardwalk freezing 

module/input/SensorFilter/data/config/SensorFilter.yaml, module/input/SensorFilter/data/config/webots/SensorFilter.yaml, module/input/SensorFilter/src/SensorFilter.cpp, module/input/SensorFilter/src/SensorFilter.hpp, module/input/SensorFilter/src/sensorfilter/update_odometry.cpp, shared/utility/math/filter/MahonyFilter.hpp
This pull request introduces adaptive proportional gain (`Kp`) functionality to the Mahony filter, allowing it to adjust based on the system's stability state (e.g., standing vs. dynamic states). The idea is to allow faster convergence when standing and sensor noise is minimal, but reduce correction gains when moving.
=> Adapt mahony gains online based on STABILITY state

module/purpose/Soccer/src/Soccer.cpp
The logic with penalisation and button presses is wrong. The robot will start playing again if the middle button is pressed during penalisation (bad!), and it will also start playing again if penalisation ends and idle is still set (not too bad but mightt be annoying).
This PR fixes those issues to check idle/penalisation in the relevant spots.
=> Fix bug making the robot walk when pressing localisation reset button during penalisation

module/strategy/WalkToFieldPosition/data/config/WalkToFieldPosition.yaml
The ready position uses WalkToFieldPosition, which has a radius within the target position in which to stop walking, and then a larger radius where if it exits that larger radius it will try to get into position again. 
Error in the system makes this drift and is the reason we have a radius, but it seems the annulus region is too small and in ready it oscillates between being happy and being outside of the larger radius.
This PR increases the annulus area by decreasing the size of the inner radius (`stop_threshold`).
Tested in robocup ready a couple of times and had no oscillations :+1:
=> Prevent oscillations when in ready position

module/extension/Director/src/director/emit_state.cpp, shared/message/behaviour/Director.proto
Change what data is sent to
- Reduce the frequency of emits (watchers and done changed very frequently)
- Fix up the parentage links.
As the tasks ids aren't put in as they change too much they were originally omitted. Now the parent provider which made the task is put into each group so you can link them back.
=> Simplify the State message to reduce frequency and add a link to parent

module/localisation/FieldLocalisationNLopt/src/FieldLocalisationNLopt.cpp, module/purpose/PenaltyShootout/CMakeLists.txt, module/purpose/PenaltyShootout/README.md, module/purpose/PenaltyShootout/data/config/PenaltyShootout.yaml, module/purpose/PenaltyShootout/src/PenaltyShootout.cpp, module/purpose/PenaltyShootout/src/PenaltyShootout.hpp, roles/penaltyshootout.role, roles/webots/penaltyshootout.role, shared/message/localisation/Field.proto
The PR adds in a new module and roles to run penalty shootouts with GameController. 
When taking a penalty kick, the robot will dribble the ball into the goals. When defending, the robot will stand still, since rules require it to not step off the line. This should be further developed. 
In either state, the idea is to press the middle button to trigger localisation to reset, which uses the field description to figure out suitable position candidates.
=> Penalty behaviour (kick taker and goalie)
